!TCL=233, 
!TITLE=Cúram Online Help
!SORT=N
!CHARSET=ANSI

!TEXT=-----------------------------------------------------------
DO NOT USE, THIS IS A DIVIDER ELEMENT.
!
!TEXT=Links
DO NOT USE, THIS IS A DIVIDER ELEMENT.
!
!TEXT=-----------------------------------------------------------
DO NOT USE, THIS IS A DIVIDER ELEMENT.
!
!TEXT=View
Click the View link on the appropriate row to view the xxxx record.
!
!TEXT=Edit
Click the Edit link on the appropriate row to modify the xxxx record.
!
!TEXT=Select
Click the Select link on the appropriate row to select the xxxx record.
!
!TEXT=Remove
Click the Remove link to remove the record.
!
!TEXT=-----------------------------------------------------------
DO NOT USE, THIS IS A DIVIDER ELEMENT.
!
!TEXT=Buttons
DO NOT USE, THIS IS A DIVIDER ELEMENT.
!
!TEXT=-----------------------------------------------------------
DO NOT USE, THIS IS A DIVIDER ELEMENT.
!
!TEXT=Save - For New page
The Save action creates a new record from the information entered on the page.
!
!TEXT=Save - For Modify page
The Save action updates the record using the information entered on the page.
!
!TEXT=Save & New
The Save & New action creates a new record from the information entered on the page and resets the page allowing an additional record to be created.
!
!TEXT=Cancel
The Cancel action dismisses the page.
!
!TEXT=Close
The Close action dismisses the page.
!
!TEXT=Search
To search for an xxxx, press the Search button to open the xxxx Search pop-up window. Enter some or all of the search criteria and search for xxxx with matching criteria. To select the xxxx, click the Select link on the appropriate row from the list of xxxx displayed.
!
!TEXT=New
The New action allows you to create a new xxxx record.
!
!TEXT=Edit
The Edit action allows you to modify the information displayed.
!
!TEXT=Delete
The Delete action allows you to delete the xxxx record.
!
!TEXT=Yes
Select Yes if you want to delete the xxxx.
!
!TEXT=No
Select No if you do not want to delete the xxxx.
!
!TEXT=-----------------------------------------------------------
DO NOT USE, THIS IS A DIVIDER ELEMENT.
!
!TEXT=View/Create/Modify/Delete Pages
DO NOT USE, THIS IS A DIVIDER ELEMENT.
!
!TEXT=-----------------------------------------------------------
DO NOT USE, THIS IS A DIVIDER ELEMENT.
!
!TEXT=View Page
This page allows you to view a xxxx record.
!
!TEXT=List View Page
This page allows you to view a list of the xxxx recorded in the system.
!
!TEXT=Create Page
This page allows you to create a xxxx record.
!
!TEXT=Modify Page
This page allows you to modify a xxxx record.
!
!TEXT=Delete Page
This page allows you to confirm the deletion of a xxxx record.
!
!TEXT=-----------------------------------------------------------
DO NOT USE, THIS IS A DIVIDER ELEMENT.
!
!TEXT=Miscellaneous
DO NOT USE, THIS IS A DIVIDER ELEMENT.
!
!TEXT=-----------------------------------------------------------
DO NOT USE, THIS IS A DIVIDER ELEMENT.
!
!TEXT=Help Page Description
Help.PageDescription=Double_click_to_enter_text 
!
!TEXT=Topic Marker
Help.Xref.1.Topicname=Double_click_to_enter_topic_marker 
!
!TEXT=Comments
User comments on this record. 
!
!TEXT=Status
Status of the xxxx. The status is "active", unless the record has been deleted, in which case, the status is "canceled". 
!
!TEXT=Cúram spelling
C\u00FAram 
!