//>>built
define("curam/matrix/TempDivs",["dijit","dojo","dojox"],function(_1,_2,_3){
_2.provide("curam.matrix.TempDivs");
_2.declare("curam.matrix.TempDivs",null,{constructor:function(_4){
this.node=_2.byId("temp-elements");
this.scroll=_2.byId("scroll");
this.num=_2.byId("num-width");
this.numHeight=this.num.offsetHeight;
this.numWidth=this.num.offsetWidth;
_4.questionColWidth=_2.byId("ques-text-width").offsetWidth;
_4.answersColWidth=_2.byId("ans-values-width").offsetWidth;
this.ctAnsVal=_2.byId("ct-ans-val");
this.ctAnsSelect=_2.byId("select");
this.image=_2.byId("image");
this.numAns=_2.byId("num-ans");
this.strAns=_2.byId("str-ans");
this.textAns=_2.byId("bool-ans");
this.priorityHeading=_2.byId("priority-heading");
this.priVal=_2.byId("pri-val");
this.cell=_2.byId("cell");
this.cellInput=_2.byId("cell-input");
}});
});
