-- default template

INSERT INTO  ST_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (stpropertiesseq.nextval, 'CONFIG','BI.UNDEFINED','Undefined','STRING',NULL,'en',s_getDateTime());

