------------------------------------------------------------------------------

-- all demo data in this file is shipped as sample, these objects are 

-- subject to change without notice, do not create custom dependencies 

-- on sample or demo objects

------------------------------------------------------------------------------

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1151,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Salt Lake');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1152,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Utah');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1153,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Morgan');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1154,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Sevier');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1155,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Beaver');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1156,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Iron');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1157,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Beaver');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1158,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Duchesne');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1159,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Beaver');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1160,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Morgan');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1161,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Sevier');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1162,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Millard');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1163,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Beaver');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1164,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Box Elder');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1165,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Sevier');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1166,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Iron');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1167,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Duchesne');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1168,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Carbon');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1169,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Utah');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1170,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Beaver');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1171,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Iron');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1172,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Rich');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1173,'232','Oak Lawn Apartments','Zinfadel','Midway','UT','US','United States',49,'Davis');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1174,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Sevier');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1175,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Piute');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1176,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Piute');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1177,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Beaver');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1178,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Box Elder');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1179,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Box Elder');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1180,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Beaver');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1181,'1153','Mole Street','Town Center','Midway','UT','US','United States',49,'Wasatch');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1182,'101','Mole Street','Mole Street','Midway','UT','US','United States',49,'Wasatch');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1183,'24','LemonTree Street','Town Center','Midway','UT','US','United States',49,'Uintah');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1184,'1','LemonTree Street','Town Center','Midway','UT','US','United States',49,'Uintah');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1185,'1','LemonTree Street','Town Center','Midway','UT','US','United States',49,'Utah');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1186,'1074','Park Terrace','Fairfield','Midway','UT','US','United States',49,'Morgan');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1187,'1074','Park Terrace','Fairfield','Midway','UT','US','United States',49,'Iron');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1188,'1074','Park Terrace','Fairfield','Midway','UT','US','United States',49,'Iron');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1189,'1074','Park Terrace','Fairfield','Midway','UT','US','United States',49,'Box Elder');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1190,'1074','Park Terrace','Fairfield','Midway','UT','US','United States',49,'Daggett');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1191,'314','Old Road','Zinfadel','Midway','UT','US','United States',49,'Washington');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1192,'232','Oak Lawn Apartments','Zinfadel','Midway','UT','US','United States',49,'Beaver');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1193,'232','Oak Lawn Apartments','Zinfadel','Midway','UT','US','United States',49,'Daggett');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1194,'123','Bridge Road','Fairfield','Midway','UT','US','United States',49,'Daggett');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1195,'433','School Drive','Fairfield','Midway','UT','US','United States',49,'Beaver');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1196,'343','School Avenue','New Port','Midway','UT','US','United States',49,'Iron');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1197,'232','Elementary Lane','Zinfadel','Midway','UT','US','United States',49,'Juab');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1198,'324','Hill Rise','Fairfield','Midway','UT','US','United States',49,'Emery');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1199,'2344','Bridge Road','New Port','Midway','UT','US','United States',49,'Salt Lake');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1200,'216','School Drive','Zinfadel','Midway','UT','US','United States',49,'Davis');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1201,'6767','School Avenue','Fairfield','Midway','UT','US','United States',49,'Davis');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1202,'2766','Elementary Lane','New Port','Midway','UT','US','United States',49,'Iron');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1203,'4244','Hill Rise','Fairfield','Midway','UT','US','United States',49,'Box Elder');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1204,'6678','Mole Street','Zinfadel','Midway','UT','US','United States',49,'Salt Lake');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1205,'2344','Jones Avenue','Fairfield','Midway','UT','US','United States',49,'Salt Lake');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1206,'2466','Oak Road','New Port','Midway','UT','US','United States',49,'Salt Lake');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1207,'1777','Cape Fear Point','Fairfield','Midway','IL','US','United States',17,'Juab');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1208,'8742','Lotts Road','Zinfadel','Midway','IL','US','United States',17,'San Juan');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1209,'2943','Highway 223','Fairfield','Midway','UT','US','United States',49,'Beaver');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1210,'854','Backtown Alley','New Port','Midway','UT','US','United States',49,'Beaver');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1211,'2943','Highway 223','Fairfield','Midway','UT','US','United States',49,'Beaver');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1212,'654','Highway 443','Zinfadel','Midway','UT','US','United States',49,'Summit');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1213,'654','Highway 136','Fairfield','Midway','UT','US','United States',49,'Iron');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1214,'234','Highway 678','New Port','Midway','UT','US','United States',49,'Box Elder');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1215,'22','Highway 43','Fairfield','Midway','UT','US','United States',49,'Grand');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1216,'343','Junction 38','Zinfadel','Midway','UT','US','United States',49,'Box Elder');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1217,'5423','Junction 654','Fairfield','Midway','UT','US','United States',49,'Juab');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1218,'434','Junction 23','New Port','Midway','UT','US','United States',49,'San Juan');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1219,'127','Mole Street','Zinfadel','Midway','UT','US','United States',49,'Iron');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1220,'378','Jones Avenue','New Port','Midway','UT','US','United States',49,'Beaver');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1221,'497','Mole Street','Fairfield','Midway','UT','US','United States',49,'Utah');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1222,'4545','Cape Fear Point','Zinfadel','Midway','UT','US','United States',49,'Tooele');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1223,'1289','Lotts Road','Fairfield','Midway','UT','US','United States',49,'Juab');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1224,'','Head Office Road','New Port','Midway','UT','US','United States',49,'Beaver');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1225,'232','Backtown Alley','Zinfadel','Midway','UT','US','United States',49,'Sanpete');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1226,'233','Head Office Road','New Port','Midway','UT','US','United States',49,'Tooele');

INSERT  INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1227,'29','Block A','LemonTree Street','Midway','UT','US','United States',49,'Garfield');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1228,'30','Greater Region','LemonTree Street','Midway','UT','US','United States',49,'Kane');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1229,'31','PO Box 621','LemonTree Street','Midway','UT','US','United States',49,'Garfield');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1230,'4234','Hill Rise','Fairfield','Midway','UT','US','United States',49,'Washington');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1231,'67','Wheaton','Citywest','Midway','UT','US','United States',49,'Salt Lake');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1232,'112','Johns Bridge Walk','Citywest','Midway','UT','US','United States',49,'Washington');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1233,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Salt Lake');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1234,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Beaver');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1235,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Iron');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1236,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Washington');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1237,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Beaver');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1238,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Salt Lake');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1239,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Beaver');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1240,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Summit');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1241,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Iron');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1242,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Juab');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1243,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Iron');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1244,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Utah');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1245,'Registered Address 1','Registered Address 2','Registered Address 3','Registered City','UT','US','United States',48,'Beaver');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1246,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Iron');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1247,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Salt Lake');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1248,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Cache');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1249,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Salt Lake');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1250,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Carbon');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1251,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Utah');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1252,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Salt Lake');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1253,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Cache');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1254,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Weber');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1255,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Salt Lake');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1256,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Cache');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1257,'232','Oak Lawn Apartments','Zinfadel','Midway','UT','US','United States',49,'Weber');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1258,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Cache');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1259,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Beaver');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1260,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Weber');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1261,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Carbon');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1262,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Kane');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1263,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Kane');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1264,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Carbon');

INSERT INTO DM_DIMADDRESS (DIMADDRESSKEY,ADDRESS1,ADDRESS2,ADDRESS3,CITY,STATE,COUNTRYCODE,COUNTRYDESC,STATEFIPSCODE,COUNTY) VALUES (1265,'Grafton Street','Dublin 2','Demodata.default.addressline3','City','UT','US','United States',49,'Iron');

