------------------------------------------------------------------------------

-- all demo data in this file is shipped as sample, these objects are 

-- subject to change without notice, do not create custom dependencies 

-- on sample or demo objects

------------------------------------------------------------------------------

INSERT INTO DM_AGGCASEDAY (ORGUNITKEY,DIMPRODUCTKEY,TIMEPERIODKEY,NOOPENCASES,NOSUBMITTEDCASES,NOAPPROVEDCASES,NOACTIVECASES,NOPENDINGCLOSECASES)

VALUES (1,5,48682,32,35,63,90,130);

INSERT INTO DM_AGGCASEDAY (ORGUNITKEY,DIMPRODUCTKEY,TIMEPERIODKEY,NOOPENCASES,NOSUBMITTEDCASES,NOAPPROVEDCASES,NOACTIVECASES,NOPENDINGCLOSECASES)

VALUES (1,3,48682,56,23,44,76,97);

INSERT INTO DM_AGGCASEDAY (ORGUNITKEY,DIMPRODUCTKEY,TIMEPERIODKEY,NOOPENCASES,NOSUBMITTEDCASES,NOAPPROVEDCASES,NOACTIVECASES,NOPENDINGCLOSECASES)

VALUES (1,4,48682,19,42,43,122,37);

INSERT INTO DM_AGGCASEDAY (ORGUNITKEY,DIMPRODUCTKEY,TIMEPERIODKEY,NOOPENCASES,NOSUBMITTEDCASES,NOAPPROVEDCASES,NOACTIVECASES,NOPENDINGCLOSECASES)

VALUES (1,2,48682,102,109,54,90,81);

INSERT INTO DM_AGGCASEDAY (ORGUNITKEY,DIMPRODUCTKEY,TIMEPERIODKEY,NOOPENCASES,NOSUBMITTEDCASES,NOAPPROVEDCASES,NOACTIVECASES,NOPENDINGCLOSECASES)

VALUES (1,1,48682,65,45,12,57,24);

INSERT INTO DM_AGGCASEDAY (ORGUNITKEY,DIMPRODUCTKEY,TIMEPERIODKEY,NOOPENCASES,NOSUBMITTEDCASES,NOAPPROVEDCASES,NOACTIVECASES,NOPENDINGCLOSECASES)

VALUES (2,5,48682,32,113,43,89,77);

INSERT INTO DM_AGGCASEDAY (ORGUNITKEY,DIMPRODUCTKEY,TIMEPERIODKEY,NOOPENCASES,NOSUBMITTEDCASES,NOAPPROVEDCASES,NOACTIVECASES,NOPENDINGCLOSECASES)

VALUES (2,4,48682,116,93,74,26,30);

INSERT INTO DM_AGGCASEDAY (ORGUNITKEY,DIMPRODUCTKEY,TIMEPERIODKEY,NOOPENCASES,NOSUBMITTEDCASES,NOAPPROVEDCASES,NOACTIVECASES,NOPENDINGCLOSECASES)

VALUES (2,3,48682,176,122,143,122,137);

INSERT INTO DM_AGGCASEDAY (ORGUNITKEY,DIMPRODUCTKEY,TIMEPERIODKEY,NOOPENCASES,NOSUBMITTEDCASES,NOAPPROVEDCASES,NOACTIVECASES,NOPENDINGCLOSECASES)

VALUES (2,2,48682,52,19,34,10,21);

INSERT INTO DM_AGGCASEDAY (ORGUNITKEY,DIMPRODUCTKEY,TIMEPERIODKEY,NOOPENCASES,NOSUBMITTEDCASES,NOAPPROVEDCASES,NOACTIVECASES,NOPENDINGCLOSECASES)

VALUES (2,1,48682,34,25,112,90,23);

INSERT INTO DM_AGGCASEDAY (ORGUNITKEY,DIMPRODUCTKEY,TIMEPERIODKEY,NOOPENCASES,NOSUBMITTEDCASES,NOAPPROVEDCASES,NOACTIVECASES,NOPENDINGCLOSECASES)

VALUES (3,5,48682,65,32,34,67,77);

INSERT INTO DM_AGGCASEDAY (ORGUNITKEY,DIMPRODUCTKEY,TIMEPERIODKEY,NOOPENCASES,NOSUBMITTEDCASES,NOAPPROVEDCASES,NOACTIVECASES,NOPENDINGCLOSECASES)

VALUES (3,3,48682,56,23,44,76,97);

INSERT INTO DM_AGGCASEDAY (ORGUNITKEY,DIMPRODUCTKEY,TIMEPERIODKEY,NOOPENCASES,NOSUBMITTEDCASES,NOAPPROVEDCASES,NOACTIVECASES,NOPENDINGCLOSECASES)

VALUES (3,4,48682,99,12,43,22,37);

INSERT INTO DM_AGGCASEDAY (ORGUNITKEY,DIMPRODUCTKEY,TIMEPERIODKEY,NOOPENCASES,NOSUBMITTEDCASES,NOAPPROVEDCASES,NOACTIVECASES,NOPENDINGCLOSECASES)

VALUES (3,2,48682,102,109,54,90,81);

INSERT INTO DM_AGGCASEDAY (ORGUNITKEY,DIMPRODUCTKEY,TIMEPERIODKEY,NOOPENCASES,NOSUBMITTEDCASES,NOAPPROVEDCASES,NOACTIVECASES,NOPENDINGCLOSECASES)

VALUES (3,1,48682,15,45,5,57,24);

INSERT INTO DM_AGGCASEDAY (ORGUNITKEY,DIMPRODUCTKEY,TIMEPERIODKEY,NOOPENCASES,NOSUBMITTEDCASES,NOAPPROVEDCASES,NOACTIVECASES,NOPENDINGCLOSECASES)

VALUES (4,5,48682,32,113,43,89,77);

INSERT INTO DM_AGGCASEDAY (ORGUNITKEY,DIMPRODUCTKEY,TIMEPERIODKEY,NOOPENCASES,NOSUBMITTEDCASES,NOAPPROVEDCASES,NOACTIVECASES,NOPENDINGCLOSECASES)

VALUES (4,3,48682,16,93,74,26,30);

INSERT INTO DM_AGGCASEDAY (ORGUNITKEY,DIMPRODUCTKEY,TIMEPERIODKEY,NOOPENCASES,NOSUBMITTEDCASES,NOAPPROVEDCASES,NOACTIVECASES,NOPENDINGCLOSECASES)

VALUES (4,4,48682,176,122,143,122,137);

INSERT INTO DM_AGGCASEDAY (ORGUNITKEY,DIMPRODUCTKEY,TIMEPERIODKEY,NOOPENCASES,NOSUBMITTEDCASES,NOAPPROVEDCASES,NOACTIVECASES,NOPENDINGCLOSECASES)

VALUES (4,2,48682,52,9,34,10,21);

INSERT INTO DM_AGGCASEDAY (ORGUNITKEY,DIMPRODUCTKEY,TIMEPERIODKEY,NOOPENCASES,NOSUBMITTEDCASES,NOAPPROVEDCASES,NOACTIVECASES,NOPENDINGCLOSECASES)

VALUES (5,1,48682,34,25,12,90,23);

INSERT INTO DM_AGGCASEDAY (ORGUNITKEY,DIMPRODUCTKEY,TIMEPERIODKEY,NOOPENCASES,NOSUBMITTEDCASES,NOAPPROVEDCASES,NOACTIVECASES,NOPENDINGCLOSECASES)

VALUES (5,2,48682,56,23,44,76,97);

INSERT INTO DM_AGGCASEDAY (ORGUNITKEY,DIMPRODUCTKEY,TIMEPERIODKEY,NOOPENCASES,NOSUBMITTEDCASES,NOAPPROVEDCASES,NOACTIVECASES,NOPENDINGCLOSECASES)

VALUES (5,3,48682,99,12,43,22,37);

