------------------------------------------------------------------------------

-- all demo data in this file is shipped as sample, these objects are 

-- subject to change without notice, do not create custom dependencies 

-- on sample or demo objects

------------------------------------------------------------------------------

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(1,5,5,2,1,4,48917,2,48936,1,3,5001,7,9,1,1);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(2,6,1,1,1,5,48920,1,48937,2,7,5002,3,9,1,2);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(3,7,2,3,2,4,48921,2,48939,1,10,5003,23,18,1,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(4,8,4,1,-1,5,49281,2,49282,3,7,5004,12,4,1,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(5,9,3,1,1,4,48923,1,48941,3,10,5005,3,7,2,1);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(6,10,1,1,-1,4,49281,1,49282,1,15,5006,17,2,2,2);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(7,11,5,1,1,5,48926,1,48943,2,9,5007,23,6,2,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(8,12,3,2,2,5,48927,2,48946,1,7,5008,7,19,2,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(9,13,1,2,-1,4,49282,1,49282,3,10,5009,10,21,3,1);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(10,14,3,2,2,5,48929,1,48949,1,12,5010,12,17,3,2);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(11,15,3,2,-1,4,48930,2,48950,3,17,5012,20,5,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(12,16,3,2,2,4,48931,1,48951,2,7,5013,29,20,3,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(13,17,2,3,1,5,48933,2,48952,1,6,5014,4,2,4,1);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(14,3,3,3,-1,5,48934,2,48953,2,19,5015,19,10,4,2);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(15,1,1,3,2,4,48935,1,48954,3,16,5016,9,17,4,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(16,4,5,3,-1,5,49281,1,49282,2,3,5017,3,16,4,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(17,3,2,1,2,5,48937,1,48945,3,0,5018,13,19,5,1);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(18,10,4,2,1,5,48938,2,48945,1,4,5019,16,13,5,2);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(19,11,3,3,2,4,48939,2,48959,2,19,5020,13,19,5,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(20,12,2,1,2,5,48941,1,48960,2,15,5021,19,24,5,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(21,13,1,2,1,4,48942,2,48961,1,9,5022,1,10,6,1);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(22,14,5,3,-1,4,49282,1,49282,1,3,5023,2,19,6,2);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(23,15,2,2,2,5,48944,2,48963,3,10,5024,18,16,6,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(24,16,3,3,1,5,48945,1,48965,1,19,5025,19,23,6,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(25,17,1,1,2,4,48946,2,48964,3,16,5026,3,9,7,1);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(26,1,5,2,-1,5,49282,1,49282,3,17,5027,12,17,7,2);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(27,2,4,3,2,5,48949,2,48968,3,8,5028,21,13,7,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(28,3,2,1,1,4,48950,1,48969,2,3,5029,17,16,7,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(29,4,1,2,2,4,48951,2,48970,1,10,5030,18,20,1,1);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(30,5,5,3,-1,5,48952,1,48971,3,4,5031,1,18,1,1);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(31,6,2,2,2,5,48953,1,48973,1,8,5032,11,9,1,1);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(32,7,3,2,-1,4,49281,2,49282,3,19,5033,21,1,1,1);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(33,8,4,3,2,5,48957,1,48975,2,6,5034,20,19,7,1);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(34,9,5,1,2,4,48959,1,48976,3,1,5035,19,14,7,1);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(35,10,1,2,-1,4,49282,2,49282,1,20,5036,21,9,7,1);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(36,11,3,3,2,5,48961,1,48978,1,18,5037,8,10,7,1);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(37,12,5,1,1,5,48962,2,48979,2,12,5038,17,21,7,1);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(38,13,1,1,1,5,48963,1,48983,3,23,5039,16,19,7,1);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(39,14,2,2,-1,4,49281,2,49282,3,21,5040,17,8,5,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(40,15,2,3,2,5,48965,1,48985,2,0,5041,7,3,5,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(41,6,5,1,2,4,48967,2,48984,3,7,5042,18,28,5,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(42,2,4,2,-1,4,48968,1,48985,1,2,5043,22,19,5,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(43,5,2,3,1,5,48969,2,48986,2,9,5044,21,17,5,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(44,3,1,1,-1,5,48970,1,48987,2,0,5045,17,21,5,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(45,3,1,1,2,5,48971,1,48988,1,2,5046,17,21,5,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(46,6,4,2,1,5,48972,1,48989,1,5,5047,7,3,5,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(47,6,1,3,-1,4,48973,2,48975,2,10,5048,11,2,1,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(48,9,3,1,-1,5,49281,1,49282,3,15,5049,9,1,1,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(49,5,2,2,2,4,48976,2,48977,1,13,5050,12,18,1,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(50,7,4,1,-1,4,48977,1,48978,2,16,5051,19,2,1,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(51,5,1,2,1,5,48978,2,48979,2,11,5052,3,19,1,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(52,4,5,1,-1,5,49282,1,49282,1,8,5053,18,10,1,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(53,5,2,2,2,4,48980,2,48981,1,5,5054,9,2,1,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(54,6,4,1,1,4,48981,1,48983,2,6,5055,2,1,1,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(55,7,2,3,-1,5,49282,2,49282,3,3,5056,7,18,1,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(56,8,1,1,2,4,48984,1,48985,1,17,5057,20,12,1,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(57,9,3,3,-1,4,49282,2,49282,2,15,5058,17,3,1,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(58,10,2,2,2,5,48986,1,48987,2,21,5059,19,21,1,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(59,11,1,3,1,4,48987,1,48988,2,7,5060,6,18,1,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(60,12,3,1,2,5,48988,2,48989,3,3,5061,29,28,1,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(61,13,5,3,-1,4,49281,1,49282,3,9,5062,18,17,1,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(62,14,5,1,2,5,48953,1,48957,2,5,5063,5,34,2,2);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(63,15,1,2,-1,4,49282,2,49282,1,11,5064,21,18,2,2);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(64,11,3,2,-1,4,48957,1,48960,1,12,5065,3,19,2,2);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(65,3,4,1,1,4,48959,2,48961,2,18,5066,4,3,2,2);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(66,5,2,2,2,4,48960,1,48962,3,9,5067,17,28,2,2);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(67,5,1,1,1,5,48961,2,48963,1,6,5068,21,22,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(68,8,5,3,-1,5,49281,1,49282,3,12,5069,21,10,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(69,9,2,1,2,5,48963,2,48965,1,15,5070,4,8,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(70,2,4,3,1,5,48964,1,48967,3,20,5071,18,3,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(71,1,3,1,1,4,48965,1,48968,3,16,5072,18,10,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(72,7,2,2,-1,5,49281,2,49282,3,10,5073,17,4,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(73,8,1,3,1,4,48968,2,48970,2,2,5074,1,3,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(74,3,5,1,2,4,48969,1,48971,1,7,5075,4,10,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(75,9,2,2,-1,5,49281,1,49282,1,6,5076,18,11,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(76,2,3,3,2,4,48971,2,48973,3,1,5077,27,4,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(77,9,1,2,-1,5,48972,1,48975,1,18,5078,3,17,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(78,2,5,1,1,4,48973,1,48976,3,22,5079,1,22,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(79,11,4,3,-1,5,49281,2,49281,2,1,5080,2,8,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(80,15,1,2,-1,5,49282,1,49282,1,1,5081,19,9,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(81,13,5,3,-1,4,49281,1,49282,3,9,5082,18,17,1,4);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(82,14,5,1,2,5,49277,1,49284,2,5,5083,5,34,2,2);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(83,15,1,2,-1,4,49282,2,49282,1,11,5084,21,18,2,2);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(84,11,3,2,-1,4,49279,1,49281,1,12,5085,3,19,2,2);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(85,3,4,1,1,4,49280,2,49284,2,18,5086,4,3,2,2);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(86,5,2,2,2,4,49277,1,49284,3,9,5087,17,28,2,2);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(87,5,1,1,1,5,49284,2,49284,1,6,5088,21,22,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(88,8,5,3,-1,5,49281,1,49282,3,12,5089,21,10,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(89,9,2,1,2,5,49284,2,49284,1,15,5090,4,8,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(90,2,4,3,1,5,49280,1,49284,3,20,5091,18,3,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(91,1,3,1,1,4,49279,1,49281,3,16,5092,18,10,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(92,7,2,2,-1,5,49281,2,49282,3,10,5093,17,4,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(93,8,1,3,1,4,49283,2,49284,2,2,5094,1,3,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(94,3,5,1,2,4,49284,1,49284,1,7,5095,4,10,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(95,9,2,2,-1,5,49281,1,49282,1,6,5096,18,11,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(96,2,3,3,2,4,49279,2,49284,3,1,5097,27,4,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(97,9,1,2,-1,5,49277,1,49284,1,18,5098,3,17,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(98,2,5,1,1,4,49280,1,49284,3,22,5099,1,22,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(99,11,4,3,-1,5,49281,2,49281,2,1,5100,2,8,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(100,15,1,2,-1,5,49282,1,49282,1,1,5101,19,9,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(101,1,3,1,1,4,49279,1,49281,3,16,5102,18,10,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(102,7,2,2,-1,5,49277,2,49282,3,10,5103,17,4,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(103,8,1,3,1,4,49282,2,49284,2,2,5104,1,3,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(104,3,5,1,2,4,49283,1,49284,1,7,5105,4,10,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(105,9,2,2,-1,5,49281,1,49282,1,6,5106,18,11,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(106,2,3,3,2,4,49279,2,49284,3,1,5107,27,4,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(107,9,1,2,-1,5,49277,1,49284,1,18,5108,3,17,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(108,2,5,1,1,4,49280,1,49284,3,22,5109,1,22,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(109,11,4,3,-1,5,49281,2,49281,2,1,5110,2,8,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID, DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,HOUROFDAY,CASEID,NUMHOURSTODISPOSE,NUMHOURSTOREC,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(110,15,1,2,-1,5,49282,1,49282,1,1,5111,19,9,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID,  DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(111,17,5,1,1,-1,-1,2,-1,1,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID,  DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(112,17,5,1,1,3,-1,1,-1,1,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID,  DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(113,17,5,1,2,2,-1,2,-1,1,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID,  DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(114,17,5,1,2,2,-1,1,-1,1,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID,  DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(115,17,5,1,1,-1,-1,2,-1,1,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID,  DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(116,17,5,1,1,-1,-1,2,-1,1,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID,  DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(117,17,5,1,1,2,-1,1,-1,1,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID,  DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(118,17,5,1,2,3,-1,1,-1,1,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID,  DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(119,17,5,1,1,1,-1,2,-1,1,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID,  DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(120,17,5,1,2,2,-1,1,-1,1,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID,  DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(121,17,5,1,1,3,-1,1,-1,1,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID,  DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(122,17,5,1,1,1,-1,2,-1,1,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID,  DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(123,17,5,1,2,3,-1,2,-1,1,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID,  DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(124,17,5,1,2,1,-1,1,-1,1,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID,  DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(125,17,5,1,2,3,-1,1,-1,1,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID,  DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(126,17,5,1,1,1,-1,1,-1,1,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID,  DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(127,17,5,1,1,3,-1,2,-1,1,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID,  DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(128,17,5,1,1,1,-1,2,-1,1,3,3);

INSERT INTO DM_FACTPROGRAMAPPLICATION(INTAKEPROGRAMAPPLICATIONID,  DIMINTAKETYPEKEY,  DIMINTAKECATEGORYKEY, DIMRESPONSEPRIORITYKEY ,DIMTIMELINESSKEY, DISPOSITIONKEY, INTAKESTARTDATEKEY,  DIMRECOMMENDATIONKEY, DISPOSEDDATEKEY, RESPONDSWITHINTIMEKEY,DIMCONTACTTYPEKEY,DIMCONTACTMETHODKEY) VALUES(129,17,5,1,1,-1,-1,2,-1,1,3,3);

