-- cleared and onhand

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) 

VALUES (dmpropertiesseq.nextval, 'CASESTATUS','StatusCategory.Onhand','On hand','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) 

VALUES (dmpropertiesseq.nextval, 'CASESTATUS','StatusCategory.Cleared','Cleared','STRING',NULL,'en',dm_getDateTime());   

-- days of the week

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','Week.Monday','Monday','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','Week.Tuesday','Tuesday','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','Week.Wednesday','Wednesday','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','Week.Thursday','Thursday','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','Week.Friday','Friday','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','Week.Saturday','Saturday','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','Week.Sunday','Sunday','STRING',NULL,'en',dm_getDateTime());   

-- Months of the year

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','Month.January','January','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','Month.February','February','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','Month.March','March','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','Month.April','April','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','Month.May','May','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','Month.June','June','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','Month.July','July','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','Month.August','August','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','Month.September','September','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','Month.October','October','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','Month.November','November','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','Month.December','December','STRING',NULL,'en',dm_getDateTime());   

-- short month names

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','MonthShortName.Jan','Jan','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','MonthShortName.Feb','Feb','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','MonthShortName.Mar','Mar','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','MonthShortName.Apr','Apr','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','MonthShortName.May','May','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','MonthShortName.Jun','Jun','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','MonthShortName.Jul','Jul','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','MonthShortName.Aug','Aug','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','MonthShortName.Sep','Sep','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','MonthShortName.Oct','Oct','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','MonthShortName.Nov','Nov','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','MonthShortName.Dec','Dec','STRING',NULL,'en',dm_getDateTime());   

-- Quarters

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','Quarter.Q1','Quarter 1','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','Quarter.Q2','Quarter 2','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','Quarter.Q3','Quarter 3','STRING',NULL,'en',dm_getDateTime());   

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','Quarter.Q4','Quarter 4','STRING',NULL,'en',dm_getDateTime());   

 -- remaining items 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'TIMEPERIOD','TIMEPERIODLEVEL.WeekOf','Week of','STRING',NULL,'en',dm_getDateTime());   

-- Age Groups

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','Core.Core.0.-.19.0.19','0-19','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','Core.Core.20.-.29.20.29','20-29','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','Core.Core.30.-.39.30.39','30-39','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','Core.Core.40.-.49.40.49','40-49','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','Core.Core.50.-.59.50.59','50-59','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','Core.Core.60.-.69.60.69','60-69','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','Core.Core.70.-.79.70.79','70-79','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','Core.Core.over.80.80.100','>80','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','Child.CG10005.0.-.1.0.1','0-1','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','Child.CG10005.2.-.5.2.5','2-5','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','Child.CG10005.6.-.11.6.11','6-11','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','Child.CG10005.12.-.15.12.15','12-15','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','Child.CG10005.16.-.19.16.19','16-19','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','Adult.CG10005.under.20.0.20','<20','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','Adult.CG10005.20.-.29.20.29','20-29','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','Adult.CG10005.30.-.39.30.39','30-39','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','Adult.CG10005.40.-.49.40.49','40-49','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','Adult.CG10005.over.49.49.100','>49','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','CG1.CG1.Under.1.0.1','<1','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','CG1.CG1.1.-.5.1.5','1-5','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','CG1.CG1.6.-.12.6.12','6-12','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','CG1.CG1.13.-.14.13.14','13-14','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','CG1.CG1.15.-.18.15.18','15-18','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','CG1.CG1.19.-.20.19.20','19-20','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','CG1.CG1.21.-.44.21.44','21-44','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','CG1.CG1.45.-.64.45.64','45-64','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','CG1.CG1.65.-.74.65.74','65-74','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','CG1.CG1.75.-.84.75.84','75-84','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','CG1.CG1.over.85.85.200','>85','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','CG1.CG1.AGE.GROUP.UNKNOWN.0.0','unknown','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','CCS.CCSINV.0-3.0.3','0-3','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','CCS.CCSINV.4-7.4.7','4-7','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','CCS.CCSINV.8-11.8.11','8-11','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','CCS.CCSINV.12-15.12.15','12-15','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','CCS.CCSINV.16-19.16.19','16-19','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','CCS.CCSINV.over.19.20.200','>19','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','Default.CCS.0-2.0.2','Infant/Toddler','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','Default.CCS.3-5.3.5','Preschool','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','Default.CCS.6-12.6.12','SchoolAge','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'AGEGROUPS','Default.CCS.13-18.13.18','Teens','STRING',NULL,'en',dm_getDateTime()); 

-- Recurrence

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'RECURRENCE','Maltreatment.CCS_REC02','No Recurrence','STRING',NULL,'en',dm_getDateTime()); 

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval,'RECURRENCE','Maltreatment.CCS_REC03','Maltreatment Recurrence','STRING',NULL,'en',dm_getDateTime()); 

-- Yes No Dim

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID, BICATEGORY, BIPROP_NAME, BIPROP_VALUE, BIPROP_TYPE, DEFAULTVALUE, LOCALE, LASTWRITTEN) VALUES (dmpropertiesseq.nextval, 'RECURRENCE', 'Maltreatment.YES', 'Yes', 'STRING', NULL, 'en', dm_getDateTime());  

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID, BICATEGORY, BIPROP_NAME, BIPROP_VALUE, BIPROP_TYPE, DEFAULTVALUE, LOCALE, LASTWRITTEN) VALUES (dmpropertiesseq.nextval, 'RECURRENCE', 'Maltreatment.NO', 'No', 'STRING', NULL, 'en', dm_getDateTime());  

INSERT INTO  DM_PROPERTIES  (BIPROPERTYID, BICATEGORY, BIPROP_NAME, BIPROP_VALUE, BIPROP_TYPE, DEFAULTVALUE, LOCALE, LASTWRITTEN) VALUES (dmpropertiesseq.nextval, 'RECURRENCE', 'Maltreatment.Unknown', 'Unknown', 'STRING', NULL, 'en', dm_getDateTime());  

