-- default template

INSERT INTO  ST_PROPERTIES  (BIPROPERTYID, BICATEGORY, BIPROP_NAME, BIPROP_VALUE, BIPROP_TYPE, DEFAULTVALUE, LOCALE, LASTWRITTEN) 

VALUES (stpropertiesseq.nextval, 'FUNDDATANAME', 'BenefitSample.Federal.Fund.2005', 'Benefit Sample Federal Fund', 'STRING', NULL, 'en', s_getDateTime());  

INSERT INTO  ST_PROPERTIES  (BIPROPERTYID, BICATEGORY, BIPROP_NAME, BIPROP_VALUE, BIPROP_TYPE, DEFAULTVALUE, LOCALE, LASTWRITTEN) 

VALUES (stpropertiesseq.nextval, 'FUNDDATANAME', 'BenefitSample.Federal.Fund.2006', 'Benefit Sample Federal Fund', 'STRING', NULL, 'en', s_getDateTime());

INSERT INTO  ST_PROPERTIES  (BIPROPERTYID, BICATEGORY, BIPROP_NAME, BIPROP_VALUE, BIPROP_TYPE, DEFAULTVALUE, LOCALE, LASTWRITTEN) 

VALUES (stpropertiesseq.nextval, 'FUNDDATANAME', 'Food.Stamps.State.Fund.2005', 'Food Stamps State Fund', 'STRING', NULL, 'en', s_getDateTime());

INSERT INTO  ST_PROPERTIES  (BIPROPERTYID, BICATEGORY, BIPROP_NAME, BIPROP_VALUE, BIPROP_TYPE, DEFAULTVALUE, LOCALE, LASTWRITTEN) 

VALUES (stpropertiesseq.nextval, 'FUNDDATANAME', 'Food.Stamps.State.Fund.2006', 'Food Stamps State Fund', 'STRING', NULL, 'en', s_getDateTime());

INSERT INTO  ST_PROPERTIES  (BIPROPERTYID, BICATEGORY, BIPROP_NAME, BIPROP_VALUE, BIPROP_TYPE, DEFAULTVALUE, LOCALE, LASTWRITTEN) 

VALUES (stpropertiesseq.nextval, 'FUNDDATANAME', 'Food.Stamps.State.Fund.2007', 'Food Stamps State Fund', 'STRING', NULL, 'en', s_getDateTime());

INSERT INTO  ST_PROPERTIES  (BIPROPERTYID, BICATEGORY, BIPROP_NAME, BIPROP_VALUE, BIPROP_TYPE, DEFAULTVALUE, LOCALE, LASTWRITTEN) 

VALUES (stpropertiesseq.nextval, 'FUNDDATANAME', 'Food.Stamps.State.Fund.2008', 'Food Stamps State Fund', 'STRING', NULL, 'en', s_getDateTime());

INSERT INTO  ST_PROPERTIES  (BIPROPERTYID, BICATEGORY, BIPROP_NAME, BIPROP_VALUE, BIPROP_TYPE, DEFAULTVALUE, LOCALE, LASTWRITTEN) 

VALUES (stpropertiesseq.nextval, 'FUNDDATANAME', 'Food.Stamps.State.Fund.2009', 'Food Stamps State Fund', 'STRING', NULL, 'en', s_getDateTime());

INSERT INTO  ST_PROPERTIES  (BIPROPERTYID, BICATEGORY, BIPROP_NAME, BIPROP_VALUE, BIPROP_TYPE, DEFAULTVALUE, LOCALE, LASTWRITTEN) 

VALUES (stpropertiesseq.nextval, 'FUNDDATANAME', 'Sport.Grant.State.Fund.2009', 'Sport Grant State Fund', 'STRING', NULL, 'en', s_getDateTime());

