------------------------------------------------------------------------------

-- all demo data in this file is shipped as sample, these objects are 

-- subject to change without notice, do not create custom dependencies 

-- on sample or demo objects

------------------------------------------------------------------------------

INSERT INTO DM_DIMDuplicateReason(DIMDUPREASONKEY,CODE,DESCRIPTION)  VALUES(1,'DR1', 'Input Error');

INSERT INTO DM_DIMDuplicateReason(DIMDUPREASONKEY,CODE,DESCRIPTION) VALUES(2,'DR2','Misuse of Identity');

INSERT INTO DM_DIMPersonType(DIMPERSONTYPEKEY,CODE, PERSONTYPE) VALUES(1,'RL1','Person');

INSERT INTO DM_DIMPersonType(DIMPERSONTYPEKEY,CODE,PERSONTYPE) VALUES(2,'RL7', 'Prospect Person');

INSERT INTO DM_DIMPersonType(DIMPERSONTYPEKEY,CODE,PERSONTYPE) VALUES(3,'RL2','Employer');

INSERT INTO DM_DIMPersonType(DIMPERSONTYPEKEY,CODE,PERSONTYPE) VALUES(4,'RL3','Service Supplier');

INSERT INTO DM_DIMPersonType(DIMPERSONTYPEKEY,CODE,PERSONTYPE) VALUES(5,'RL4','Product Provider');

INSERT INTO DM_DIMPersonType(DIMPERSONTYPEKEY,CODE,PERSONTYPE) VALUES(6,'RL5','Information Provider');

INSERT INTO DM_DIMPersonType(DIMPERSONTYPEKEY,CODE,PERSONTYPE) VALUES(7,'RL6','Utility');

INSERT INTO DM_DIMPersonType(DIMPERSONTYPEKEY,CODE,PERSONTYPE) VALUES(8,'RL8','Prospect Employer');

INSERT INTO DM_DIMPersonType(DIMPERSONTYPEKEY,CODE,PERSONTYPE) VALUES(9,'RL9','Representative');

INSERT INTO DM_DIMPersonType(DIMPERSONTYPEKEY,CODE,PERSONTYPE) VALUES(10,'RL10','External Party');

INSERT INTO DM_DIMPersonType(DIMPERSONTYPEKEY,CODE,PERSONTYPE) VALUES(11,'RL11','Provider');

INSERT INTO DM_DIMPersonType(DIMPERSONTYPEKEY,CODE,PERSONTYPE) VALUES(12,'RL12','Provider Group');

INSERT INTO DM_DIMMergeStatus(DIMMERGESTATUSKEY,CODE,DESCRIPTION) VALUES(1,'MS1','Not Merged');

INSERT INTO DM_DIMMergeStatus(DIMMERGESTATUSKEY,CODE,DESCRIPTION) VALUES(2,'MS2','In Merged');

INSERT INTO DM_DIMMergeStatus(DIMMERGESTATUSKEY,CODE,DESCRIPTION) VALUES(3,'MS3','Merged Complete');

INSERT INTO DM_DIMDuplicateStatus(DIMDUPSTATUSKEY,CODE,DESCRIPTION) VALUES(1,'DS1','Marked');

INSERT INTO DM_DIMDuplicateStatus(DIMDUPSTATUSKEY,CODE,DESCRIPTION) VALUES(2,'DS2','Unmarked');

INSERT INTO DM_DIMASSISTANCESTATUS (DIMASSISTANCESTATUSKEY,CODE,DESCRIPTION) VALUES (1,'NON','Non Assistance');

INSERT INTO DM_DIMASSISTANCESTATUS (DIMASSISTANCESTATUSKEY,CODE,DESCRIPTION) VALUES (2,'PUBLIC','Public Assistance');

INSERT INTO DM_DIMBOECODES (DIMBOEKEY,CODE,DESCRIPTION) VALUES (1, '9','BOE Unknown');

INSERT INTO DM_DIMBOECODES (DIMBOEKEY,CODE,DESCRIPTION) VALUES (2, '1','Aged');

INSERT INTO DM_DIMBOECODES (DIMBOEKEY,CODE,DESCRIPTION) VALUES (3, '2','Blind/Disabled' );

INSERT INTO DM_DIMBOECODES (DIMBOEKEY,CODE,DESCRIPTION) VALUES (4, '4','Children' );

INSERT INTO DM_DIMBOECODES (DIMBOEKEY,CODE,DESCRIPTION) VALUES (5, '5','Adult' );

INSERT INTO DM_DIMBOECODES (DIMBOEKEY,CODE,DESCRIPTION) VALUES (6, '8','Foster Care Children' );

INSERT INTO DM_DIMBOECODES (DIMBOEKEY,CODE,DESCRIPTION) VALUES (7, 'A','BCCA Women' );

INSERT INTO DM_DIMCASEOWNER (CASEOWNERKEY, CASEOWNERNAME) VALUES (1,'admin');

INSERT INTO DM_DIMCASEOWNER (CASEOWNERKEY, CASEOWNERNAME) VALUES (2,'caseworker');

INSERT INTO DM_DIMCASEOWNER (CASEOWNERKEY, CASEOWNERNAME) VALUES (3,'cpmmanager');

INSERT INTO DM_DIMCASEOWNER (CASEOWNERKEY, CASEOWNERNAME) VALUES (4,'cpmsupervisor');

INSERT INTO DM_DIMCASEOWNER (CASEOWNERKEY, CASEOWNERNAME) VALUES (5,'ctiuser');

INSERT INTO DM_DIMCASEOWNER (CASEOWNERKEY, CASEOWNERNAME) VALUES (6,'financial');

INSERT INTO DM_DIMCASEOWNER (CASEOWNERKEY, CASEOWNERNAME) VALUES (7,'ronan');

INSERT INTO DM_DIMCASEOWNER (CASEOWNERKEY, CASEOWNERNAME) VALUES (8,'superuser');

INSERT INTO DM_DIMCASEOWNER (CASEOWNERKEY, CASEOWNERNAME) VALUES (9,'supervisor');

INSERT INTO DM_DIMCASEOWNER (CASEOWNERKEY, CASEOWNERNAME) VALUES (10,'supervisorui');

INSERT INTO DM_DIMCASEOWNER (CASEOWNERKEY, CASEOWNERNAME) VALUES (11,'unauthenticated');

INSERT INTO DM_DIMCASEOWNER (CASEOWNERKEY, CASEOWNERNAME) VALUES (12,'workflow');

INSERT INTO DM_DIMCASEOWNER (CASEOWNERKEY, CASEOWNERNAME) VALUES (13,'ccsintakeworker1');

INSERT INTO DM_DIMCASEOWNER (CASEOWNERKEY, CASEOWNERNAME) VALUES (14,'ccsintakeworker2');

INSERT INTO DM_DIMCASEOWNER (CASEOWNERKEY, CASEOWNERNAME) VALUES (15,'ccsintakeworker3');

INSERT INTO DM_DIMCASEPARTICIPANTROLE (DIMCASEPARTROLEID, ROLETYPE) VALUES (1,'Applied Deduction Recipient');

INSERT INTO DM_DIMCASEPARTICIPANTROLE (DIMCASEPARTROLEID, ROLETYPE) VALUES (2,'Nominee');

INSERT INTO DM_DIMCASEPARTICIPANTROLE (DIMCASEPARTROLEID, ROLETYPE) VALUES (3,'Primary Client');

INSERT INTO DM_DIMCASEPARTICIPANTROLE (DIMCASEPARTROLEID, ROLETYPE) VALUES (4,'Product Provider');

INSERT INTO DM_DIMCASEPARTICIPANTROLE (DIMCASEPARTROLEID, ROLETYPE) VALUES (5,'Third Party Deduction Recipient');

INSERT INTO DM_DIMCASESUPER (CASESUPERKEY, CASESUPERNAME) VALUES (13,'superuser');

INSERT INTO DM_DIMCASESUPER (CASESUPERKEY, CASESUPERNAME) VALUES (14,'Supervisor A');

INSERT INTO DM_DIMCASESUPER (CASESUPERKEY, CASESUPERNAME) VALUES (15,'Supervisor B');

INSERT INTO DM_DIMCASESUPER (CASESUPERKEY, CASESUPERNAME) VALUES (16,'Supervisor C');

INSERT INTO DM_DIMCASESUPER (CASESUPERKEY, CASESUPERNAME) VALUES (17,'ccsintakesuper1');

INSERT INTO DM_DIMCASESUPER (CASESUPERKEY, CASESUPERNAME) VALUES (18,'ccsintakesuper2');

INSERT INTO DM_DIMCHILDSUPPORTENFORTYPES (DIMCHILDSUPPORTENFORCETYPEKEY,DESCRIPTION,CODE) VALUES (9,'Not Applicable','NA');

INSERT INTO DM_DIMCHILDSUPPORTENFORTYPES (DIMCHILDSUPPORTENFORCETYPEKEY,DESCRIPTION,CODE) VALUES (2,'Not Cooperated With Child Support','NO');

INSERT INTO DM_DIMCHILDSUPPORTENFORTYPES (DIMCHILDSUPPORTENFORCETYPEKEY,DESCRIPTION,CODE) VALUES (1,'Cooperated With Child Support','YES');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (1,'RT1','Parent');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (2,'RT2','Child');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (3,'RT3','Sibling');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (4,'RT4','Guardian');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (5,'RT5','Orphan');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (6,'RT6','Spouse');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (7,'RT7','Appointee');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (8,'RT8','Appointer');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (9,'RT9','Attendant');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (10,'RT10','Person Cared For');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (11,'RT11','Grand Parent');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (12,'RT12','Grand Child');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (13,'RT13','Uncle');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (14,'RT14','Aunt');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (15,'RT15','Nephew');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (16,'RT16','Niece');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (17,'RT17','Cousin');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (18,'RT18','Great Grand Parent');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (19,'RT19','Great Grand Child');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (20,'RT20','Great Uncle');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (21,'RT21','Great Aunt');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (22,'RT22','Great Niece');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (23,'RT23','Great Nephew');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (24,'RT24','Foster Parent');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (25,'RT25','Foster Child');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (26,'RT26','Un Related');

INSERT INTO DM_DIMCONCERNRELATIONSHIPTYPE (RELATIONSHIPTYPEKEY,CODE,DESCRIPTION) VALUES (27,'RT28','Self');

INSERT INTO DM_DIMCOUNTRY (DIMCOUNTRYKEY,COUNTRY) VALUES (1,'Great Britain');

INSERT INTO DM_DIMCOUNTRY (DIMCOUNTRYKEY,COUNTRY) VALUES (2,'United States');

INSERT INTO DM_DIMCOUNTRY (DIMCOUNTRYKEY,COUNTRY) VALUES (3,'Australia');

INSERT INTO DM_DIMCOUNTRY (DIMCOUNTRYKEY,COUNTRY) VALUES (4,'New Zealand');

INSERT INTO DM_DIMCOUNTRY (DIMCOUNTRYKEY,COUNTRY) VALUES (5,'Germany');

INSERT INTO DM_DIMCOUNTRY (DIMCOUNTRYKEY,COUNTRY) VALUES (6,'India');

INSERT INTO DM_DIMDELIVERYMETHOD (DIMDELIVERYMETHODKEY, DELIVERYMETHOD) VALUES (1,'Cash');

INSERT INTO DM_DIMDELIVERYMETHOD (DIMDELIVERYMETHODKEY, DELIVERYMETHOD) VALUES (2,'Check');

INSERT INTO DM_DIMDELIVERYMETHOD (DIMDELIVERYMETHODKEY, DELIVERYMETHOD) VALUES (3,'Invoice');

INSERT INTO DM_DIMDELIVERYMETHOD (DIMDELIVERYMETHODKEY, DELIVERYMETHOD) VALUES (5,'Voucher');

INSERT INTO DM_DIMDEDUCTION (DIMDEDUCTIONKEY,DEDUCTIONCAT,DEDUCTIONNAME) VALUES (1,'Third Party Deduction','Electricity Deduction');

INSERT INTO DM_DIMDEDUCTION (DIMDEDUCTIONKEY,DEDUCTIONCAT,DEDUCTIONNAME) VALUES (2,'Third Party Deduction','Gas Deduction');

INSERT INTO DM_DIMDEDUCTION (DIMDEDUCTIONKEY,DEDUCTIONCAT,DEDUCTIONNAME) VALUES (3,'Third Party Deduction','Rent Deduction');

INSERT INTO DM_DIMDEDUCTION (DIMDEDUCTIONKEY,DEDUCTIONCAT,DEDUCTIONNAME) VALUES (4,'Third Party Deduction','Medical Deduction');

INSERT INTO DM_DIMDEDUCTION (DIMDEDUCTIONKEY,DEDUCTIONCAT,DEDUCTIONNAME) VALUES (5,'Unapplied Deduction','Tax Deduction');

INSERT INTO DM_DIMDEDUCTION (DIMDEDUCTIONKEY,DEDUCTIONCAT,DEDUCTIONNAME) VALUES (6,'Applied Deduction','Overpayment Deduction');

INSERT INTO DM_DIMDEDUCTION (DIMDEDUCTIONKEY,DEDUCTIONCAT,DEDUCTIONNAME) VALUES (7,'Applied Deduction','Repayment Deduction');

INSERT INTO DM_DIMDISPOSITION (DISPOSITIONKEY,CODE,DISPOSITIONDESC) VALUES (1,'APP','Approved');

INSERT INTO DM_DIMDISPOSITION (DISPOSITIONKEY,CODE,DISPOSITIONDESC) VALUES (2,'DEN','Denied');

INSERT INTO DM_DIMDISPOSITION (DISPOSITIONKEY,CODE,DISPOSITIONDESC) VALUES (3,'WITH','Withdrawn');

INSERT INTO DM_DIMDISPOSITION (DISPOSITIONKEY,CODE,DISPOSITIONDESC) VALUES (4,'DC1','Screened In');

INSERT INTO DM_DIMDISPOSITION (DISPOSITIONKEY,CODE,DISPOSITIONDESC) VALUES (5,'DC2','Screened Out');

INSERT INTO DM_DIMDUALELIGIBILITY (DIMDUALKEY,DESCRIPTION) VALUES (1,'Not A Dual Eligible Product');

INSERT INTO DM_DIMDUALELIGIBILITY (DIMDUALKEY,CODE,DESCRIPTION) VALUES (2,'PN36','QMB');

INSERT INTO DM_DIMDUALELIGIBILITY (DIMDUALKEY,CODE,DESCRIPTION) VALUES (3,'PN37','SLMB');

INSERT INTO DM_DIMDUALELIGIBILITY (DIMDUALKEY,CODE,DESCRIPTION) VALUES (4,'PN39','QDWI');

INSERT INTO DM_DIMDUALELIGIBILITY (DIMDUALKEY,CODE,DESCRIPTION) VALUES (5,'PN38','QI(1)');

INSERT INTO DM_DIMEDUCATION (DIMEDUCATIONKEY,QUALIFICATION) VALUES (1,'Degree');

INSERT INTO DM_DIMEDUCATION (DIMEDUCATIONKEY,QUALIFICATION) VALUES (2,'Diploma');

INSERT INTO DM_DIMEDUCATION (DIMEDUCATIONKEY,QUALIFICATION) VALUES (3,'Master');

INSERT INTO DM_DIMEDUCATION (DIMEDUCATIONKEY,QUALIFICATION) VALUES (4,'Certificate');

INSERT INTO DM_DIMEDUCATION (DIMEDUCATIONKEY,QUALIFICATION) VALUES (5,'Doctorate');

INSERT INTO DM_DIMEDUCATIONLEVELS (DIMEDUCATIONLEVELKEY,CODE,DESCRIPTION) VALUES (1,'SG1','First Grade');

INSERT INTO DM_DIMEDUCATIONLEVELS (DIMEDUCATIONLEVELKEY,CODE,DESCRIPTION) VALUES (2,'SG2','Second Grade');

INSERT INTO DM_DIMEDUCATIONLEVELS (DIMEDUCATIONLEVELKEY,CODE,DESCRIPTION) VALUES (3,'SG3','Third Grade');

INSERT INTO DM_DIMEDUCATIONLEVELS (DIMEDUCATIONLEVELKEY,CODE,DESCRIPTION) VALUES (7,'SG7','Seventh Grade');

INSERT INTO DM_DIMEDUCATIONLEVELS (DIMEDUCATIONLEVELKEY,CODE,DESCRIPTION) VALUES (6,'SG6','Sixth Grade');

INSERT INTO DM_DIMEDUCATIONLEVELS (DIMEDUCATIONLEVELKEY,CODE,DESCRIPTION) VALUES (5,'SG5','Fifth Grade');

INSERT INTO DM_DIMEDUCATIONLEVELS (DIMEDUCATIONLEVELKEY,CODE,DESCRIPTION) VALUES (4,'SG4','Fourth Grade');

INSERT INTO DM_DIMEDUCATIONLEVELS (DIMEDUCATIONLEVELKEY,CODE,DESCRIPTION) VALUES (98,'SG24','No Formal Education');

INSERT INTO DM_DIMEDUCATIONLEVELS (DIMEDUCATIONLEVELKEY,CODE,DESCRIPTION) VALUES (16,'SG16','Other Credentials');

INSERT INTO DM_DIMEDUCATIONLEVELS (DIMEDUCATIONLEVELKEY,CODE,DESCRIPTION) VALUES (15,'SG15','Awarded graduate degree');

INSERT INTO DM_DIMEDUCATIONLEVELS (DIMEDUCATIONLEVELKEY,CODE,DESCRIPTION) VALUES (14,'SG14','Awarded Bachelors Degree');

INSERT INTO DM_DIMEDUCATIONLEVELS (DIMEDUCATIONLEVELKEY,CODE,DESCRIPTION) VALUES (13,'SG13','Awarded Associates Degree');

INSERT INTO DM_DIMEDUCATIONLEVELS (DIMEDUCATIONLEVELKEY,CODE,DESCRIPTION) VALUES (12,'SG12','Diploma GED');

INSERT INTO DM_DIMEDUCATIONLEVELS (DIMEDUCATIONLEVELKEY,CODE,DESCRIPTION) VALUES (11,'SG11','Eleventh Grade');

INSERT INTO DM_DIMEDUCATIONLEVELS (DIMEDUCATIONLEVELKEY,CODE,DESCRIPTION) VALUES (10,'SG10','Thenth Grade ');

INSERT INTO DM_DIMEDUCATIONLEVELS (DIMEDUCATIONLEVELKEY,CODE,DESCRIPTION) VALUES (9,'SG9','Ninth Grade');

INSERT INTO DM_DIMEDUCATIONLEVELS (DIMEDUCATIONLEVELKEY,CODE,DESCRIPTION) VALUES (8,'SG8','Eight Grade');

INSERT INTO DM_DIMEMPLOYMENTSTATUS (DIMEMPLOYMENTSTATUSKEY, CODE, DESCRIPTION) VALUES (1,'Emp','Employed');

INSERT INTO DM_DIMEMPLOYMENTSTATUS (DIMEMPLOYMENTSTATUSKEY, CODE, DESCRIPTION) VALUES (2,'NotEmp','Not Employed');

INSERT INTO DM_DIMEMPLOYMENTSTATUS (DIMEMPLOYMENTSTATUSKEY, CODE, DESCRIPTION) VALUES (3,'NotLabFor','Not In Labour Force');

INSERT INTO DM_DIMETHNICITY (DIMETHNICITYKEY, ETHNICITY) VALUES (1,'Hispanic or Latino');

INSERT INTO DM_DIMETHNICITY (DIMETHNICITYKEY, ETHNICITY) VALUES (2,'Not Hispanic or Latino');

INSERT INTO DM_DIMFINANCIALSTATUS (DIMFINSTATUSKEY,STATUSCODE,STATUSDESC) VALUES (1,'SUS','Suspended');

INSERT INTO DM_DIMFINANCIALSTATUS (DIMFINSTATUSKEY,STATUSCODE,STATUSDESC) VALUES (2,'ALL','Allocated');

INSERT INTO DM_DIMFINANCIALSTATUS (DIMFINSTATUSKEY,STATUSCODE,STATUSDESC) VALUES (3,'REC','Reconciled');

INSERT INTO DM_DIMFINANCIALSTATUS (DIMFINSTATUSKEY,STATUSCODE,STATUSDESC) VALUES (4,'PRO','Processed');

INSERT INTO DM_DIMFINANCIALSTATUS (DIMFINSTATUSKEY,STATUSCODE,STATUSDESC) VALUES (5,'UNP','Unprocessed');

INSERT INTO DM_DIMFINANCIALSTATUS (DIMFINSTATUSKEY,STATUSCODE,STATUSDESC) VALUES (6,'REV','Reversed');

INSERT INTO DM_DIMFINANCIALSTATUS (DIMFINSTATUSKEY,STATUSCODE,STATUSDESC) VALUES (7,'CAN','Canceled');

INSERT INTO DM_DIMFINANCIALSTATUS (DIMFINSTATUSKEY,STATUSCODE,STATUSDESC) VALUES (8,'EXP','Expired');

INSERT INTO DM_DIMFINANCIALSTATUS (DIMFINSTATUSKEY,STATUSCODE,STATUSDESC) VALUES (9,'TRF','Transferred');

INSERT INTO DM_DIMFUND (DIMFUNDID,REVENUE,FUNDNAME,DWPRODUCTID) VALUES (1,10000000,'BenefitSample Federal Fund 2005',2);

INSERT INTO DM_DIMFUND (DIMFUNDID,REVENUE,FUNDNAME,DWPRODUCTID) VALUES (2,11000000,'BenefitSample Federal Fund 2006',3);

INSERT INTO DM_DIMFUND (DIMFUNDID,REVENUE,FUNDNAME,DWPRODUCTID) VALUES (5,25000000,'Food Stamps State Fund 2007',4);

INSERT INTO DM_DIMFUND (DIMFUNDID,REVENUE,FUNDNAME,DWPRODUCTID) VALUES (6,26000000,'Food Stamps State Fund 2008',5);

INSERT INTO DM_DIMFUND (DIMFUNDID,REVENUE,FUNDNAME,DWPRODUCTID) VALUES (7,26000000,'Food Stamps State Fund 2009',9);

INSERT INTO DM_DIMFUND (DIMFUNDID,REVENUE,FUNDNAME,DWPRODUCTID) VALUES (8,26000000,'Sport Grant State Fund 2009',12);

INSERT INTO DM_DIMGENDER (DIMGENDERKEY,GENDER) VALUES (15,'Female');

INSERT INTO DM_DIMGENDER (DIMGENDERKEY,GENDER) VALUES (16,'Male');

INSERT INTO DM_DIMINDUSTRYTYPE (DIMINDUSTRYTYPEKEY,INDUSTRYTYPE) VALUES (1,'Education');

INSERT INTO DM_DIMINDUSTRYTYPE (DIMINDUSTRYTYPEKEY,INDUSTRYTYPE) VALUES (2,'Engineering');

INSERT INTO DM_DIMINDUSTRYTYPE (DIMINDUSTRYTYPEKEY,INDUSTRYTYPE) VALUES (3,'Telecommunications');

INSERT INTO DM_DIMINDUSTRYTYPE (DIMINDUSTRYTYPEKEY,INDUSTRYTYPE) VALUES (4,'Construction');

INSERT INTO DM_DIMINDUSTRYTYPE (DIMINDUSTRYTYPEKEY,INDUSTRYTYPE) VALUES (5,'Local Government');

INSERT INTO DM_DIMMARITALSTATUS (DIMMARITALSTATUSKEY, MARITALSTATUS) VALUES (1,'Divorced');

INSERT INTO DM_DIMMARITALSTATUS (DIMMARITALSTATUSKEY, MARITALSTATUS) VALUES (2,'Married');

INSERT INTO DM_DIMMARITALSTATUS (DIMMARITALSTATUSKEY, MARITALSTATUS) VALUES (3,'Seperated');

INSERT INTO DM_DIMMARITALSTATUS (DIMMARITALSTATUSKEY, MARITALSTATUS) VALUES (4,'Single');

INSERT INTO DM_DIMMASCODES (DIMMASKEY,CODE,DESCRIPTION) VALUES (1, '9', 'MAS Unknown');

INSERT INTO DM_DIMMASCODES (DIMMASKEY,CODE,DESCRIPTION) VALUES (2, '1', 'Receiving Cash');

INSERT INTO DM_DIMMASCODES (DIMMASKEY,CODE,DESCRIPTION) VALUES (3, '2', 'Medically Needy');

INSERT INTO DM_DIMMASCODES (DIMMASKEY,CODE,DESCRIPTION) VALUES (4, '3', 'Poverty Related');

INSERT INTO DM_DIMMASCODES (DIMMASKEY,CODE,DESCRIPTION) VALUES (5, '4', 'Other');

INSERT INTO DM_DIMMASCODES (DIMMASKEY,CODE,DESCRIPTION) VALUES (6, '4', 'Waiver');

INSERT INTO DM_DIMNUMOFPARENTS (DIMNUMOFPARENTSKEY,NUMOFPARENTS) VALUES (1,0);

INSERT INTO DM_DIMNUMOFPARENTS (DIMNUMOFPARENTSKEY,NUMOFPARENTS) VALUES (2,1);

INSERT INTO DM_DIMNUMOFPARENTS (DIMNUMOFPARENTSKEY,NUMOFPARENTS) VALUES (3,2);

INSERT INTO DM_DIMNUMOFPARENTS (DIMNUMOFPARENTSKEY,NUMOFPARENTS) VALUES (4,3);

INSERT INTO DM_DIMORGANISATION (DIMORGKEY,ORGNAME,STATE) VALUES (1,'Midway Social Welfare Organization','Utah');

INSERT INTO DM_DIMORGUNIT (ORGUNITKEY,ORGUNITID,ORGUNITNAME,ORGUNITDESC,ORGUNITLEVEL,ORGUNITPARENTID,ORGUNITPARENTNAME)VALUES 

(1,1,'Board of Directors','Demo data Midway Board of Directors',1,null,null);

INSERT INTO DM_DIMORGUNIT (ORGUNITKEY,ORGUNITID,ORGUNITNAME,ORGUNITDESC,ORGUNITLEVEL,ORGUNITPARENTID,ORGUNITPARENTNAME)VALUES

(2,2,'Ronans work unit','Demo data for Ronans work unit',2,1,null);

INSERT INTO DM_DIMORGUNIT (ORGUNITKEY,ORGUNITID,ORGUNITNAME,ORGUNITDESC,ORGUNITLEVEL,ORGUNITPARENTID,ORGUNITPARENTNAME)VALUES

(3,3,'Model Office','Model Office',2,1,null);

INSERT INTO DM_DIMORGUNIT (ORGUNITKEY,ORGUNITID,ORGUNITNAME,ORGUNITDESC,ORGUNITLEVEL,ORGUNITPARENTID,ORGUNITPARENTNAME)VALUES

(4,4,'Ministry of Health','Ministry of Health',3,2,null);

INSERT INTO DM_DIMORGUNIT (ORGUNITKEY,ORGUNITID,ORGUNITNAME,ORGUNITDESC,ORGUNITLEVEL,ORGUNITPARENTID,ORGUNITPARENTNAME)VALUES

(5,5,'Studylink','Studylink',3,2,null);

INSERT INTO DM_DIMORGUNIT (ORGUNITKEY,ORGUNITID,ORGUNITNAME,ORGUNITDESC,ORGUNITLEVEL,ORGUNITPARENTID,ORGUNITPARENTNAME)VALUES

(6,1,'Board of Directors','Board of Directors',1,1,'Board of Directors');

INSERT INTO DM_DIMORGUNIT (ORGUNITKEY,ORGUNITID,ORGUNITNAME,ORGUNITDESC,ORGUNITLEVEL,ORGUNITPARENTID,ORGUNITPARENTNAME)VALUES

(7,2,'Ronans work unit','Ronans work unit',2,1,'Board of Directors');

INSERT INTO DM_DIMORGUNIT (ORGUNITKEY,ORGUNITID,ORGUNITNAME,ORGUNITDESC,ORGUNITLEVEL,ORGUNITPARENTID,ORGUNITPARENTNAME)VALUES

(8,3,'Model Office','Model Office',2,1,'Board of Directors');

INSERT INTO DM_DIMORGUNIT (ORGUNITKEY,ORGUNITID,ORGUNITNAME,ORGUNITDESC,ORGUNITLEVEL,ORGUNITPARENTID,ORGUNITPARENTNAME)VALUES

(9,4,'Ministry of Health','Ministry of Health',3,1,'Board of Directors');

INSERT INTO DM_DIMORGUNIT (ORGUNITKEY,ORGUNITID,ORGUNITNAME,ORGUNITDESC,ORGUNITLEVEL,ORGUNITPARENTID,ORGUNITPARENTNAME)VALUES

(10,5,'Studylink','Studylink',3,1,'Board of Directors');

INSERT INTO DM_DIMORGUNIT (ORGUNITKEY,ORGUNITID,ORGUNITNAME,ORGUNITDESC,ORGUNITLEVEL,ORGUNITPARENTID,ORGUNITPARENTNAME)VALUES

(11,2,'Ronans work unit','Ronans work unit',2,2,'Ronans work unit');

INSERT INTO DM_DIMORGUNIT (ORGUNITKEY,ORGUNITID,ORGUNITNAME,ORGUNITDESC,ORGUNITLEVEL,ORGUNITPARENTID,ORGUNITPARENTNAME)VALUES

(12,4,'Ministry of Health','Ministry of Health',3,2,'Ronans work unit');

INSERT INTO DM_DIMORGUNIT (ORGUNITKEY,ORGUNITID,ORGUNITNAME,ORGUNITDESC,ORGUNITLEVEL,ORGUNITPARENTID,ORGUNITPARENTNAME)VALUES

(13,5,'Studylink','Studylink',3,2,'Ronans work unit');

INSERT INTO DM_DIMORGUNIT (ORGUNITKEY,ORGUNITID,ORGUNITNAME,ORGUNITDESC,ORGUNITLEVEL,ORGUNITPARENTID,ORGUNITPARENTNAME)VALUES

(14,3,'Model Office','Model Office',2,3,'Model Office');

INSERT INTO DM_DIMORGUNIT (ORGUNITKEY,ORGUNITID,ORGUNITNAME,ORGUNITDESC,ORGUNITLEVEL,ORGUNITPARENTID,ORGUNITPARENTNAME)VALUES

(15,4,'Ministry of Health','Ministry of Health',3,4,'Ministry of Health');

INSERT INTO DM_DIMORGUNIT (ORGUNITKEY,ORGUNITID,ORGUNITNAME,ORGUNITDESC,ORGUNITLEVEL,ORGUNITPARENTID,ORGUNITPARENTNAME)VALUES

(16,5,'Studylink','Studylink',3,5,'Studylink');

INSERT INTO DM_DIMPAYMETHOD (DIMPAYMETHODKEY,PAYMETHODDESC) VALUES (1,'Cash'); 

INSERT INTO DM_DIMPAYMETHOD (DIMPAYMETHODKEY,PAYMETHODDESC) VALUES (2,'Cheque'); 

INSERT INTO DM_DIMPAYMETHOD (DIMPAYMETHODKEY,PAYMETHODDESC) VALUES (3,'Direct Debit'); 

INSERT INTO DM_DIMPAYMETHOD (DIMPAYMETHODKEY,PAYMETHODDESC) VALUES (4,'Bank Draft'); 

INSERT INTO DM_DIMPAYMETHOD (DIMPAYMETHODKEY,PAYMETHODDESC) VALUES (5,'Postal Order'); 

INSERT INTO DM_DIMPAYMETHOD (DIMPAYMETHODKEY,PAYMETHODDESC) VALUES (6,'Giro');

INSERT INTO DM_DIMPREFERREDLANGUAGE (DIMPREFERREDLANGUAGEKEY,PREFERREDLANGUAGE) VALUES (1,'English');

INSERT INTO DM_DIMPREFERREDLANGUAGE (DIMPREFERREDLANGUAGEKEY,PREFERREDLANGUAGE) VALUES (2,'French');

INSERT INTO DM_DIMPARTICIPANTSTATUS (DIMPARTICIPANTSTATUSKEY,STATUS) VALUES (1,'Active');

INSERT INTO DM_DIMPARTICIPANTSTATUS (DIMPARTICIPANTSTATUSKEY,STATUS) VALUES (2,'Closed');

INSERT INTO DM_DIMPARTICIPANTSTATUS (DIMPARTICIPANTSTATUSKEY,STATUS) VALUES (3,'Suspended');

INSERT INTO DM_DIMPARTICIPANTSTATUS (DIMPARTICIPANTSTATUSKEY,STATUS) VALUES (4,'Archived');

INSERT INTO DM_DIMPARTICIPANTSTATUS (DIMPARTICIPANTSTATUSKEY,STATUS) VALUES (5,'Temporary');

INSERT INTO DM_DIMPARTICIPANTSTATUS (DIMPARTICIPANTSTATUSKEY,STATUS) VALUES (6,'Transferred');

INSERT INTO DM_DIMPRODUCT (DIMPRODUCTKEY,DWPRODUCTID,NAME,PRODUCTTYPECODE, PRODUCTTYPE) VALUES (1,-6620291452234629120,'PN26','PT1','Benefit Sample');

INSERT INTO DM_DIMPRODUCT (DIMPRODUCTKEY,DWPRODUCTID,NAME,PRODUCTTYPECODE, PRODUCTTYPE) VALUES (2,2101,'Benefit Sample', 'PT1', 'Benefit Sample');

INSERT INTO DM_DIMPRODUCT (DIMPRODUCTKEY,DWPRODUCTID,NAME,PRODUCTTYPECODE, PRODUCTTYPE) VALUES (3,2102,'Curam Sample Benefit Overpayment Product','PT4','Benefit Overpayment');

INSERT INTO DM_DIMPRODUCT (DIMPRODUCTKEY,DWPRODUCTID,NAME,PRODUCTTYPECODE, PRODUCTTYPE) VALUES (4,2103,'Curam Sample Liability Overpayment Product','PT5','Liability Overpayment');

INSERT INTO DM_DIMPRODUCT (DIMPRODUCTKEY,DWPRODUCTID,NAME,PRODUCTTYPECODE, PRODUCTTYPE) VALUES (5,2104,'Liability Sample','PT7','Liability Sample');

INSERT INTO DM_DIMPRODUCT (DIMPRODUCTKEY,DWPRODUCTID,NAME,PRODUCTTYPECODE, PRODUCTTYPE) VALUES (6,2105,'Class A Contribution Product','PT8','Class A Contribution');

INSERT INTO DM_DIMPRODUCT (DIMPRODUCTKEY,DWPRODUCTID,NAME,PRODUCTTYPECODE, PRODUCTTYPE) VALUES (7,2106,'Class B Contribution Product','PT9','Class B Contribution');

INSERT INTO DM_DIMPRODUCT (DIMPRODUCTKEY,DWPRODUCTID,NAME,PRODUCTTYPECODE, PRODUCTTYPE) VALUES (8,2107,'Class C Contribution Product','PT10','Class C Contribution');

INSERT INTO DM_DIMPRODUCT (DIMPRODUCTKEY,DWPRODUCTID,NAME,PRODUCTTYPECODE, PRODUCTTYPE) VALUES (9,2108,'Integrated Case Benefit Sample','PT1','Benefit Sample');

INSERT INTO DM_DIMPRODUCT (DIMPRODUCTKEY,DWPRODUCTID,NAME,PRODUCTTYPECODE, PRODUCTTYPE) VALUES (10,2109,'Benefit Underpayment Product','PT25','Benefit Underpayment');

INSERT INTO DM_DIMPRODUCT (DIMPRODUCTKEY,DWPRODUCTID,NAME,PRODUCTTYPECODE, PRODUCTTYPE) VALUES (11,2110,'IC Benefit Underpayment Product','PT25','Benefit Underpayment');

INSERT INTO DM_DIMPRODUCT (DIMPRODUCTKEY,DWPRODUCTID,NAME,PRODUCTTYPECODE, PRODUCTTYPE) VALUES (12,2111,'Sporting Grant Sample','PT30','Sporting Grant Sample');

INSERT INTO DM_DIMPRODUCT (DIMPRODUCTKEY,DWPRODUCTID,NAME,PRODUCTTYPECODE, PRODUCTTYPE) VALUES (13,2112,'Curam Liability Overbilling Product','PT12','Liability Overbilling');

INSERT INTO DM_DIMPRODUCT (DIMPRODUCTKEY,DWPRODUCTID,NAME,PRODUCTTYPECODE, PRODUCTTYPE) VALUES (14,5105,'Provider Invoice Case','PT501','Provider Invoice');

INSERT INTO DM_DIMPRODUCT (DIMPRODUCTKEY,DWPRODUCTID,NAME,PRODUCTTYPECODE, PRODUCTTYPE) VALUES (15,5106,'Provider Placement Case','PT502','Provider Placement');

INSERT INTO DM_DIMPRODUCT (DIMPRODUCTKEY,DWPRODUCTID,NAME,PRODUCTTYPECODE, PRODUCTTYPE) VALUES (16,5107,'Flat-Rate Contract Payments','PT503','Provider Contract');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (-2,'CS001','Child Services','Child Services');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (1,'PT16','Food Stamps','Food Stamps');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (2,'PT17','Medicaid','Medicaid');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (3,'PT22','Cash Assistance','Cash Assistance');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (100,'DP1','Other','Other');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (101,'PT1','Benefit Sample','Benefit Sample');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (102,'PT10','Class C Contribution','Class C Contribution');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (103,'PT11','Unemployment Benefit','Unemployment Benefit');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (104,'PT12','Liability Overbilling','Liability Overbilling');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (105,'PT15','Health Grant','Health Grant');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (108,'PT18','TANF','TANF');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (109,'PT19','Disaster Unemployment Assistance','Disaster Unemployment Assistance');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (110,'PT2','Training','Training');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (111,'PT20','Simple Product','Simple Product');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (112,'PT2001','Payment Correction','Payment Correction');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (113,'PT21','Simple Liability Product','Simple Liability Product');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (115,'PT2201','CREOLE Test Product Delivery','CREOLE Test Product Delivery');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (116,'PT2211','CREOLE Development Product Delivery','CREOLE Development Product Delivery');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (117,'PT23','Income Support','Income Support');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (118,'PT25','Benefit Underpayment','Benefit Underpayment');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (119,'PT2501','Employment Benefit','Employment Benefit');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (120,'PT26','******','******');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (121,'PT27','Liability Underpayment','Liability Underpayment');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (122,'PT3','Contribution Liability','Contribution Liability');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (123,'PT30','Sporting Grant Sample','Sporting Grant Sample');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (124,'PT4','Benefit Overpayment','Benefit Overpayment');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (125,'PT5','Liability Overpayment','Liability Overpayment');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (126,'PT6','Contribution Training','Contribution Training');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (127,'PT7','Liability Sample','Liability Sample');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (128,'PT8','Class A Contribution','Class A Contribution');

INSERT INTO DM_DIMPROGRAM (DIMPROGRAMKEY,PROGRAMCODE,PROGRAM,DISPLAYNAME) VALUES (129,'PT9','Class B Contribution','Class B Contribution');

INSERT INTO DM_DIMSERVICE (DIMSERVICEKEY,SERVICETYPE) VALUES (1,'Medical Examinations');

INSERT INTO DM_DIMSERVICE (DIMSERVICEKEY,SERVICETYPE) VALUES (2,'Encashment of Benefit Payments');

INSERT INTO DM_DIMSERVICE (DIMSERVICEKEY,SERVICETYPE) VALUES (3,'Optical Examinations');

INSERT INTO DM_DIMSERVICE (DIMSERVICEKEY,SERVICETYPE) VALUES (4,'Dental Examinations');

INSERT INTO DM_DIMSERVICE (DIMSERVICEKEY,SERVICETYPE) VALUES (5,'Appeal Administration');

INSERT INTO DM_DIMSERVICE (DIMSERVICEKEY,SERVICETYPE) VALUES (6,'Taxation');

INSERT INTO DM_DIMSTATUS (STATUSKEY,STATUSNAME,STATUSCATEGORY)VALUES (3,'Open ','On Hand');

INSERT INTO DM_DIMSTATUS (STATUSKEY,STATUSNAME,STATUSCATEGORY)VALUES (4,'Registered ','On Hand');

INSERT INTO DM_DIMSTATUS (STATUSKEY,STATUSNAME,STATUSCATEGORY)VALUES (5,'Received ','On Hand');

INSERT INTO DM_DIMSTATUS (STATUSKEY,STATUSNAME,STATUSCATEGORY)VALUES (6,'Suspended ','On Hand');

INSERT INTO DM_DIMSTATUS (STATUSKEY,STATUSNAME,STATUSCATEGORY)VALUES (7,'Approved ','On Hand');

INSERT INTO DM_DIMSTATUS (STATUSKEY,STATUSNAME,STATUSCATEGORY)VALUES (8,'Submitted ','On Hand');

INSERT INTO DM_DIMSTATUS (STATUSKEY,STATUSNAME,STATUSCATEGORY)VALUES (9,'Pending closure ','Cleared');

INSERT INTO DM_DIMSTATUS (STATUSKEY,STATUSNAME,STATUSCATEGORY)VALUES (10,'Rejected ','Cleared');

INSERT INTO DM_DIMSTATUS (STATUSKEY,STATUSNAME,STATUSCATEGORY)VALUES (11,'Canceled ','Cleared');

INSERT INTO DM_DIMSTATUS (STATUSKEY,STATUSNAME,STATUSCATEGORY)VALUES (12,'Active ','Cleared');

INSERT INTO DM_DIMSTATUS (STATUSKEY,STATUSNAME,STATUSCATEGORY)VALUES (13,'Closed ','Cleared');

INSERT INTO DM_DIMSTATUS (STATUSKEY,STATUSNAME) VALUES (1,'On Hand');

INSERT INTO DM_DIMSTATUS (STATUSKEY,STATUSNAME) VALUES (2,'Cleared');

INSERT INTO DM_DIMSUBSIDIZEDHOUSINGTYPES (DIMSUBSIDIZEDHOUSINGTYPEKEY,CODE,DESCRIPTION) values (1,'PH','Public Housing');

INSERT INTO DM_DIMSUBSIDIZEDHOUSINGTYPES (DIMSUBSIDIZEDHOUSINGTYPEKEY,CODE,DESCRIPTION) values (2,'RS','Rent Subsidy');

INSERT INTO DM_DIMSUBSIDIZEDHOUSINGTYPES (DIMSUBSIDIZEDHOUSINGTYPEKEY,CODE,DESCRIPTION) values (3,'NA','No Housing Subsidy');

INSERT INTO DM_DIMTRANSACTIONTYPE (DIMTRANSACTIONKEY,CATEGORYCODE,CATEGORYDESC,TYPECODE,TYPEDESC,CRDRTYPE) VALUES (1,'DED','Payment Instruction For Deduction','D01','Deduction Payment','CDT');

INSERT INTO DM_DIMTRANSACTIONTYPE (DIMTRANSACTIONKEY,CATEGORYCODE,CATEGORYDESC,TYPECODE,TYPEDESC,CRDRTYPE) VALUES (2,'LBY','Liability Instruction','RBO','Benefit Overpayment','DBT');

INSERT INTO DM_DIMTRANSACTIONTYPE (DIMTRANSACTIONKEY,CATEGORYCODE,CATEGORYDESC,TYPECODE,TYPEDESC,CRDRTYPE) VALUES (3,'PMT','Payment Instruction','C04','Max Personal','DBT');

INSERT INTO DM_DIMTRANSACTIONTYPE (DIMTRANSACTIONKEY,CATEGORYCODE,CATEGORYDESC,TYPECODE,TYPEDESC,CRDRTYPE) VALUES (4,'PMT','Payment Instruction','C08','Max Dependent Child','DBT');

INSERT INTO DM_DIMTRANSACTIONTYPE (DIMTRANSACTIONKEY,CATEGORYCODE,CATEGORYDESC,TYPECODE,TYPEDESC,CRDRTYPE) VALUES (5,'PMT','Payment Instruction','D02','Deduction Item','CDT');

INSERT INTO DM_DIMTRANSACTIONTYPE (DIMTRANSACTIONKEY,CATEGORYCODE,CATEGORYDESC,TYPECODE,TYPEDESC,CRDRTYPE) VALUES (6,'PMT','Payment Instruction','TAX','Tax Payment','CDT');

INSERT INTO DM_DIMTRANSACTIONTYPE (DIMTRANSACTIONKEY,CATEGORYCODE,CATEGORYDESC,TYPECODE,TYPEDESC,CRDRTYPE) VALUES (7,'PRV','Payment Received Instruction','APR','DemoData.Transactiontype.Allocated.Payment.Received..value','CDT');

INSERT INTO DM_DIMTRANSACTIONTYPE (DIMTRANSACTIONKEY,CATEGORYCODE,CATEGORYDESC,TYPECODE,TYPEDESC,CRDRTYPE) VALUES (8,'REV','Reversal Instruction','ARV','Reverse Allocation','CDT');

INSERT INTO DM_DIMTRANSACTIONTYPE (DIMTRANSACTIONKEY,CATEGORYCODE,CATEGORYDESC,TYPECODE,TYPEDESC,CRDRTYPE) VALUES (9,'REV','Reversal Instruction','UAR','Reversal','CDT');

INSERT INTO DM_DIMTRANSACTIONTYPE (DIMTRANSACTIONKEY,CATEGORYCODE,CATEGORYDESC,TYPECODE,TYPEDESC,CRDRTYPE) VALUES (10,'WRT','Write Off Instruction','WRT','Write Off','CDT');

INSERT INTO DM_DIMTRANSACTIONTYPE (DIMTRANSACTIONKEY,CATEGORYCODE,CATEGORYDESC,TYPECODE,TYPEDESC,CRDRTYPE) VALUES (11,'LBY','Liability Instruction','L04','Employee Contribution Liability','DBT');

INSERT INTO DM_DIMTRANSACTIONTYPE (DIMTRANSACTIONKEY,CATEGORYCODE,CATEGORYDESC,TYPECODE,TYPEDESC,CRDRTYPE) VALUES (12,'PMT','Payment Instruction','C37','Food Stamps','DBT');

INSERT INTO DM_DIMTRANSACTIONTYPE (DIMTRANSACTIONKEY,CATEGORYCODE,CATEGORYDESC,TYPECODE,TYPEDESC,CRDRTYPE) VALUES (13,'PMT','Payment Instruction','UAD','Under Payment Adjustment','CDT');

INSERT INTO DM_DIMTRANSACTIONTYPE (DIMTRANSACTIONKEY,CATEGORYCODE,CATEGORYDESC,TYPECODE,TYPEDESC,CRDRTYPE) VALUES (14,'PMT','Payment Instruction','ADA','Allocated Deduction Adjustment','DBT');

INSERT INTO DM_DIMTRANSACTIONTYPE (DIMTRANSACTIONKEY,CATEGORYCODE,CATEGORYDESC,TYPECODE,TYPEDESC,CRDRTYPE) VALUES (15,'PMT','Payment Instruction','SUR','Surcharge Liability','CDT');

INSERT INTO DM_DIMTRANSACTIONTYPE (DIMTRANSACTIONKEY,CATEGORYCODE,CATEGORYDESC,TYPECODE,TYPEDESC,CRDRTYPE) VALUES (16,'PMT','Payment Instruction','C01','Ad-hoc Payment','CDT');

INSERT INTO DM_DIMTRANSACTIONTYPE (DIMTRANSACTIONKEY,CATEGORYCODE,CATEGORYDESC,TYPECODE,TYPEDESC,CRDRTYPE) VALUES (17,'PRV','Payment Instruction','UPR','Unallocated Payment Received','CDT');

INSERT INTO DM_DIMUTILITY (DIMUTILITYKEY,UTILITYTYPE) VALUES (1,'Electricity');

INSERT INTO DM_DIMUTILITY (DIMUTILITYKEY,UTILITYTYPE) VALUES (2,'Gas');

INSERT INTO DM_DIMUTILITY (DIMUTILITYKEY,UTILITYTYPE) VALUES (3,'Housing');

INSERT INTO DM_DIMUTILITY (DIMUTILITYKEY,UTILITYTYPE) VALUES (4,'Transport');

INSERT INTO DM_DIMUTILITY (DIMUTILITYKEY,UTILITYTYPE) VALUES (5,'Telephone');

INSERT INTO DM_DIMINTAKETYPE (DIMINTAKETYPEKEY,CODE,INTAKETYPEDESC) VALUES(1,'TYPCA','Child Abuse or Neglect');

INSERT INTO DM_DIMINTAKETYPE (DIMINTAKETYPEKEY,CODE,INTAKETYPEDESC) VALUES(2,'TYPCF','Child Fatality non Child Abuse neglect');

INSERT INTO DM_DIMINTAKETYPE (DIMINTAKETYPEKEY,CODE,INTAKETYPEDESC) VALUES(3,'TYPCIN','Children in Need of Services');

INSERT INTO DM_DIMINTAKETYPE (DIMINTAKETYPEKEY,CODE,INTAKETYPEDESC) VALUES(4,'TYPDC','Safe Haven Deserted Child');

INSERT INTO DM_DIMINTAKETYPE (DIMINTAKETYPEKEY,CODE,INTAKETYPEDESC) VALUES(5,'TYPEY','Emancipated Youth');

INSERT INTO DM_DIMINTAKETYPE (DIMINTAKETYPEKEY,CODE,INTAKETYPEDESC) VALUES(6,'TYPFIN','Family in Need of Services');

INSERT INTO DM_DIMINTAKETYPE (DIMINTAKETYPEKEY,CODE,INTAKETYPEDESC) VALUES(7,'TYPHE','Home Evaluation Visitation Assessment');

INSERT INTO DM_DIMINTAKETYPE (DIMINTAKETYPEKEY,CODE,INTAKETYPEDESC) VALUES(8,'TYPICAMA','Adoption');

INSERT INTO DM_DIMINTAKETYPE (DIMINTAKETYPEKEY,CODE,INTAKETYPEDESC) VALUES(9,'TYPICJ','Youth Justice');

INSERT INTO DM_DIMINTAKETYPE (DIMINTAKETYPEKEY,CODE,INTAKETYPEDESC) VALUES(10,'TYPICPC','Foster Care');

INSERT INTO DM_DIMINTAKETYPE (DIMINTAKETYPEKEY,CODE,INTAKETYPEDESC) VALUES(11,'TYPIP','Information Provided Only');

INSERT INTO DM_DIMINTAKETYPE (DIMINTAKETYPEKEY,CODE,INTAKETYPEDESC) VALUES(12,'TYPPAS','Post Finalization Adoption Services');

INSERT INTO DM_DIMINTAKETYPE (DIMINTAKETYPEKEY,CODE,INTAKETYPEDESC) VALUES(13,' TYPPSER','Preventative Services');

INSERT INTO DM_DIMINTAKETYPE (DIMINTAKETYPEKEY,CODE,INTAKETYPEDESC) VALUES(14,' TYPPSUR','Permanent Surrender');

INSERT INTO DM_DIMINTAKETYPE (DIMINTAKETYPEKEY,CODE,INTAKETYPEDESC) VALUES(15,'TYPRC','Referral to Community Agency');

INSERT INTO DM_DIMINTAKETYPE (DIMINTAKETYPEKEY,CODE,INTAKETYPEDESC) VALUES(16,'TYPUD','Unruly Delinquent');

INSERT INTO DM_DIMINTAKETYPE (DIMINTAKETYPEKEY,CODE,INTAKETYPEDESC) VALUES(17,'TYPUK','Unknown');

INSERT INTO DM_DIMINTAKECATEGORY (DIMINTAKECATEGORYKEY,CODE,DIMINTAKECATEGORYDESC) VALUES(1,'CAT1','Child Protection Services');

INSERT INTO DM_DIMINTAKECATEGORY (DIMINTAKECATEGORYKEY,CODE,DIMINTAKECATEGORYDESC) VALUES(2,'CAT2','Family Services');

INSERT INTO DM_DIMINTAKECATEGORY (DIMINTAKECATEGORYKEY,CODE,DIMINTAKECATEGORYDESC) VALUES(3,'CAT3','Information and Referral');

INSERT INTO DM_DIMINTAKECATEGORY (DIMINTAKECATEGORYKEY,CODE,DIMINTAKECATEGORYDESC) VALUES(4,'CAT4','Inter Jurisdictional Intake');

INSERT INTO DM_DIMINTAKECATEGORY (DIMINTAKECATEGORYKEY,CODE,DIMINTAKECATEGORYDESC) VALUES(5,'CAT5','Unknown');

INSERT INTO DM_DIMRECOMMENDATION(DIMRECOMMENDATIONKEY,CODE,RECOMMENDATIONDESC) VALUES(1,'DC1','Screened In');

INSERT INTO DM_DIMRECOMMENDATION(DIMRECOMMENDATIONKEY,CODE,RECOMMENDATIONDESC) VALUES(2,'DC2','Screened Out');

INSERT INTO DM_DIMRESPONSEPRIORITY(DIMRESPONSEPRIORITYKEY,CODE,RESPONSEPRIORITYDESC) VALUES(1,'CP1','High');

INSERT INTO DM_DIMRESPONSEPRIORITY(DIMRESPONSEPRIORITYKEY,CODE,RESPONSEPRIORITYDESC) VALUES(2,'CP2','Medium');

INSERT INTO DM_DIMRESPONSEPRIORITY(DIMRESPONSEPRIORITYKEY,CODE,RESPONSEPRIORITYDESC) VALUES(3,'CP3','Low');

INSERT INTO DM_DIMRESPONDSWITHINTIME(RESPONDSWITHINTIMEKEY,CODE,RESPONDSWITHINTIMEDESC) VALUES( 1,'24','24 Hours');

INSERT INTO DM_DIMRESPONDSWITHINTIME(RESPONDSWITHINTIMEKEY,CODE,RESPONDSWITHINTIMEDESC) VALUES( 2,'72','3 Days');

INSERT INTO DM_DIMRESPONDSWITHINTIME(RESPONDSWITHINTIMEKEY,CODE,RESPONDSWITHINTIMEDESC) VALUES( 3,'240','10 Days');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,0,'0 - 3');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,1,'0 - 3');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,2,'0 - 3');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,3,'0 - 3');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,4,'4 - 7');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,5,'4 - 7');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,6,'4 - 7');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,7,'4 - 7');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,8,'8 - 11');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,9,'8 - 11');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,10,'8 - 11');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,11,'8 - 11');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,12,'12 - 15');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,13,'12 - 15');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,14,'12 - 15');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,15,'12 - 15');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,16,'16 - 19');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,17,'16 - 19');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,18,'16 - 19');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,19,'16 - 19');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,20,'20 - 23');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,21,'20 - 23');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,22,'20 - 23');

INSERT INTO DM_DIMTIMEOFDAYGROUPS(DIMPROGRAMKEY,HOUROFDAY,GROUPNAME) VALUES(-2,23,'20 - 23');

INSERT INTO DM_DIMYESNOINDICATOR(DIMYESNOINDICATORKEY,INDDESCRIPTION) VALUES(1,'Yes');

INSERT INTO DM_DIMYESNOINDICATOR(DIMYESNOINDICATORKEY,INDDESCRIPTION) VALUES(2,'No');

---------------------------------------------------------------------------------------------------

--CCS Related data-----------------------------------------------------------------------------------------

---------------------------------------------------------------------------------------------------

INSERT INTO DM_DIMINTEGRATEDCASETYPES(DIMINTEGRATEDCASETYPEKEY,CODE,INTEGRATEDCASETYPE) VALUES( 1 , 'CFSS_PC10',  'Ongoing Case'  );

INSERT INTO DM_DIMINTEGRATEDCASETYPES(DIMINTEGRATEDCASETYPEKEY,CODE,INTEGRATEDCASETYPE) VALUES( 2 ,'CFSS_PC11', 'Pre-Adoption Case' );

INSERT INTO DM_DIMINTEGRATEDCASETYPES(DIMINTEGRATEDCASETYPEKEY,CODE,INTEGRATEDCASETYPE) VALUES( 3 ,'PC31',  'Adoption Subsidy Case' );

INSERT INTO DM_DIMINTEGRATEDCASETYPES(DIMINTEGRATEDCASETYPEKEY,CODE,INTEGRATEDCASETYPE) VALUES( 4 ,'PC1', 'Assistance'  );

INSERT INTO DM_DIMINTEGRATEDCASETYPES(DIMINTEGRATEDCASETYPEKEY,CODE,INTEGRATEDCASETYPE) VALUES( 5 ,'PC2', 'Illness' );

INSERT INTO DM_DIMINTEGRATEDCASETYPES(DIMINTEGRATEDCASETYPEKEY,CODE,INTEGRATEDCASETYPE) VALUES( 6 ,'PC3', 'Financial' );

INSERT INTO DM_DIMINTEGRATEDCASETYPES(DIMINTEGRATEDCASETYPEKEY,CODE,INTEGRATEDCASETYPE) VALUES( 7 ,'PC4', 'Behavioral'  );

INSERT INTO DM_DIMINTEGRATEDCASETYPES(DIMINTEGRATEDCASETYPEKEY,CODE,INTEGRATEDCASETYPE) VALUES( 8 ,'PC5', 'Social'  );

INSERT INTO DM_DIMINTEGRATEDCASETYPES(DIMINTEGRATEDCASETYPEKEY,CODE,INTEGRATEDCASETYPE) VALUES( 9 ,'PC6', 'Unimplemented');

INSERT INTO DM_DIMINTEGRATEDCASETYPES(DIMINTEGRATEDCASETYPEKEY,CODE,INTEGRATEDCASETYPE) VALUES( 10  ,'PC7', 'IncomeSupport' );

INSERT INTO DM_DIMINTEGRATEDCASETYPES(DIMINTEGRATEDCASETYPEKEY,CODE,INTEGRATEDCASETYPE) VALUES( 11  ,'PC9', 'SportingGrant' );

---------------------------------------------------------------------------------------------------------------------------------------------

INSERT INTO DM_DIMCASEREVIEWOUTCOMES(DIMCASEREVIEWOUTCOMEKEY,COMPONENTOUTCOME,OVERALLOUTCOME) VALUES( 1 , 'Conditions Satisfied'  , 'Placement' );

INSERT INTO DM_DIMCASEREVIEWOUTCOMES(DIMCASEREVIEWOUTCOMEKEY,COMPONENTOUTCOME,OVERALLOUTCOME) VALUES( 2 , 'Conditions not satisfied'  , 'Placement' );

INSERT INTO DM_DIMCASEREVIEWOUTCOMES(DIMCASEREVIEWOUTCOMEKEY,COMPONENTOUTCOME,OVERALLOUTCOME) VALUES( 3 , 'Cancelled' , 'Placement' );

--------------------------------------------------------------------------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------------------------------------------------

INSERT INTO DM_DIMINDIGENOUSGROUPS(DIMINDIGENOUSGROUPKEY,CODE,INDIGENOUSGROUP) VALUES(  1 ,'INGR2', 'Abenaki' );

INSERT INTO DM_DIMINDIGENOUSGROUPS(DIMINDIGENOUSGROUPKEY,CODE,INDIGENOUSGROUP) VALUES(  2 ,'INGR3', 'Abnaki-Penobscot'  );

INSERT INTO DM_DIMINDIGENOUSGROUPS(DIMINDIGENOUSGROUPKEY,CODE,INDIGENOUSGROUP) VALUES(  3 ,'INGR4', 'Absaaloke' );

INSERT INTO DM_DIMINDIGENOUSGROUPS(DIMINDIGENOUSGROUPKEY,CODE,INDIGENOUSGROUP) VALUES(  4 ,'INGR5', 'Achumawi'  );

INSERT INTO DM_DIMINDIGENOUSGROUPS(DIMINDIGENOUSGROUPKEY,CODE,INDIGENOUSGROUP) VALUES(  5 ,'INGR6', 'Acjachemen'  );

INSERT INTO DM_DIMINDIGENOUSGROUPS(DIMINDIGENOUSGROUPKEY,CODE,INDIGENOUSGROUP) VALUES(  6 ,'INGR7', 'Acoma' );

INSERT INTO DM_DIMINDIGENOUSGROUPS(DIMINDIGENOUSGROUPKEY,CODE,INDIGENOUSGROUP) VALUES(  7 ,'INGR8', 'Agua Caliente' );

INSERT INTO DM_DIMINDIGENOUSGROUPS(DIMINDIGENOUSGROUPKEY,CODE,INDIGENOUSGROUP) VALUES(  8 ,'INGR9', 'Ahahnelin' );

INSERT INTO DM_DIMINDIGENOUSGROUPS(DIMINDIGENOUSGROUPKEY,CODE,INDIGENOUSGROUP) VALUES(  9 ,'INGR10',  'Ahe' );

INSERT INTO DM_DIMINDIGENOUSGROUPS(DIMINDIGENOUSGROUPKEY,CODE,INDIGENOUSGROUP) VALUES(  10  ,'INGR11',  'Ahtna'  );

------------------------------------------------------------------------------------------------------------------------

INSERT INTO DM_DIMCASETYPES(DIMCASETYPEKEY,CODE,CASETYPE) VALUES( 1 ,'CFSS_CT2',  'Investigation' );

INSERT INTO DM_DIMCASETYPES(DIMCASETYPEKEY,CODE,CASETYPE) VALUES( 2 ,'CT11',  'Social Enterprise Folder'  );

INSERT INTO DM_DIMCASETYPES(DIMCASETYPEKEY,CODE,CASETYPE) VALUES( 3 ,'CFSS_CT1',  'Legal Action'  );

INSERT INTO DM_DIMCASETYPES(DIMCASETYPEKEY,CODE,CASETYPE) VALUES( 4 ,'CT60',  'Provider Invoice Case' );

INSERT INTO DM_DIMCASETYPES(DIMCASETYPEKEY,CODE,CASETYPE) VALUES( 5 ,'CT61',  'Provider Utilization Case' );

INSERT INTO DM_DIMCASETYPES(DIMCASETYPEKEY,CODE,CASETYPE) VALUES( 6 ,'CT62',  'Provider Contract Case'  );

INSERT INTO DM_DIMCASETYPES(DIMCASETYPEKEY,CODE,CASETYPE) VALUES( 7 ,'CT1', 'Service Plan'  );

INSERT INTO DM_DIMCASETYPES(DIMCASETYPEKEY,CODE,CASETYPE) VALUES( 8 ,'CT2', 'Product Delivery'  );

INSERT INTO DM_DIMCASETYPES(DIMCASETYPEKEY,CODE,CASETYPE) VALUES( 9 ,'CT4', 'Liability' );

INSERT INTO DM_DIMCASETYPES(DIMCASETYPEKEY,CODE,CASETYPE) VALUES( 10  ,'CT5', 'Integrated Case' );

INSERT INTO DM_DIMCASETYPES(DIMCASETYPEKEY,CODE,CASETYPE) VALUES( 11  ,'CT6', 'Screening Case'  );

INSERT INTO DM_DIMCASETYPES(DIMCASETYPEKEY,CODE,CASETYPE) VALUES( 12  ,'CT7', 'Assessment Delivery' );

INSERT INTO DM_DIMCASETYPES(DIMCASETYPEKEY,CODE,CASETYPE) VALUES( 13  ,'CT10',  'Issue' );

INSERT INTO DM_DIMCASETYPES(DIMCASETYPEKEY,CODE,CASETYPE) VALUES( 14  ,'CT2000',  'Investigation'  );

--------------------------------------------------------------------------------------------------------------------------------

INSERT INTO DM_DIMCONTACTTYPE(DIMCONTACTTYPEKEY,CODE,DESCRIPTION) VALUES (1,'CLT2000','Interview');

INSERT INTO DM_DIMCONTACTTYPE(DIMCONTACTTYPEKEY,CODE,DESCRIPTION) VALUES (2,'CLT2001','Office Visit');

INSERT INTO DM_DIMCONTACTTYPE(DIMCONTACTTYPEKEY,CODE,DESCRIPTION) VALUES (3,'CLT2002','Case Conference');

INSERT INTO DM_DIMCONTACTTYPE(DIMCONTACTTYPEKEY,CODE,DESCRIPTION) VALUES (4,'CLT2003','Foster Home Visit');

INSERT INTO DM_DIMCONTACTTYPE(DIMCONTACTTYPEKEY,CODE,DESCRIPTION) VALUES (5,'CLT2004','Notification');

INSERT INTO DM_DIMCONTACTTYPE(DIMCONTACTTYPEKEY,CODE,DESCRIPTION) VALUES (6,'CLT2005','Home Visit');

INSERT INTO DM_DIMCONTACTTYPE(DIMCONTACTTYPEKEY,CODE,DESCRIPTION) VALUES (7,'CLT2006','Site visit');

INSERT INTO DM_DIMCONTACTTYPE(DIMCONTACTTYPEKEY,CODE,DESCRIPTION) VALUES (8,'CLT8500','Treatment Plan');

INSERT INTO DM_DIMCONTACTTYPE(DIMCONTACTTYPEKEY,CODE,DESCRIPTION) VALUES (9,'CLT8501','Supervision Interview');

INSERT INTO DM_DIMCONTACTTYPE(DIMCONTACTTYPEKEY,CODE,DESCRIPTION) VALUES (10,'CLT8000','Scheduled Visitation');

INSERT INTO DM_DIMCONTACTTYPE(DIMCONTACTTYPEKEY,CODE,DESCRIPTION) VALUES (11,'CLT8001','Unscheduled Visitation');

INSERT INTO DM_DIMCONTACTTYPE(DIMCONTACTTYPEKEY,CODE,DESCRIPTION) VALUES (12,'CLT8002','Multi-Disciplinary Team Conference');

------------------------------------------------------------------------------------------------------------------------------

INSERT INTO DM_DIMCONTACTMETHOD(DIMCONTACTMETHODKEY,CODE,DESCRIPTION) VALUES (1,'CLM2000','Phone');

INSERT INTO DM_DIMCONTACTMETHOD(DIMCONTACTMETHODKEY,CODE,DESCRIPTION) VALUES (2,'CLM2001','E-Mail');

INSERT INTO DM_DIMCONTACTMETHOD(DIMCONTACTMETHODKEY,CODE,DESCRIPTION) VALUES (3,'CLM2002','Face to Face');

INSERT INTO DM_DIMCONTACTMETHOD(DIMCONTACTMETHODKEY,CODE,DESCRIPTION) VALUES (4,'CLM2003','Hard Copy');

INSERT INTO DM_DIMCONTACTMETHOD(DIMCONTACTMETHODKEY,CODE,DESCRIPTION) VALUES (5,'CLM8000','Mail');

INSERT INTO DM_DIMCONTACTMETHOD(DIMCONTACTMETHODKEY,CODE,DESCRIPTION) VALUES (6,'CLM8500','Fax');

------------------------------------------------------------------------------------------------------------------------------

INSERT INTO DM_DIMRACE (DIMRACEKEY,CODE,DESCRIPTION) VALUES (1,'RACE03','White');

INSERT INTO DM_DIMRACE (DIMRACEKEY,CODE,DESCRIPTION) VALUES (2,'RACE01','African American');

INSERT INTO DM_DIMRACE (DIMRACEKEY,CODE,DESCRIPTION) VALUES (3,'RACE04','Native American');

INSERT INTO DM_DIMRACE (DIMRACEKEY,CODE,DESCRIPTION) VALUES (4,'RACE05','Asian');

INSERT INTO DM_DIMRACE (DIMRACEKEY,CODE,DESCRIPTION) VALUES (5,'RACE06','Hawaiian');

INSERT INTO DM_DIMRACE (DIMRACEKEY,CODE,DESCRIPTION) VALUES (6,'RACE07','Multi Racial');

------------------------------------------------------------------------------------------------------------------------------

INSERT INTO DM_DIMCOMPLIANCETYPE (DIMCOMPLIANCETYPEKEY,COMPLIANCETYPECODE,COMPLIANCETYPEDESC)  VALUES (1,'INITIAL', 'Initial Contact Compliance');

INSERT INTO DM_DIMCOMPLIANCETYPE (DIMCOMPLIANCETYPEKEY,COMPLIANCETYPECODE,COMPLIANCETYPEDESC)  VALUES (2,'ONGOING', 'Ongoing Contact Compliance');

------------------------------------------------------------------------------------------------------------------------------

INSERT INTO DM_DIMCONTACTPURPOSE (DIMPURPOSEKEY,CONTACTLOGID, PURPOSECODE, PURPOSEDESCRIPTION) VALUES (1,44000, 'CLP2000', 'Alleged Victim Contact');

INSERT INTO DM_DIMCONTACTPURPOSE (DIMPURPOSEKEY,CONTACTLOGID, PURPOSECODE, PURPOSEDESCRIPTION) VALUES (2,44001, 'CLP2001', 'Alleged Maltreater Contact');

INSERT INTO DM_DIMCONTACTPURPOSE (DIMPURPOSEKEY,CONTACTLOGID, PURPOSECODE, PURPOSEDESCRIPTION) VALUES (3,44002, 'CLP2002', 'Case Planning Entry');

INSERT INTO DM_DIMCONTACTPURPOSE (DIMPURPOSEKEY,CONTACTLOGID, PURPOSECODE, PURPOSEDESCRIPTION) VALUES (4,44003, 'CLP2003', 'General Participant Contact Entry');

INSERT INTO DM_DIMCONTACTPURPOSE (DIMPURPOSEKEY,CONTACTLOGID, PURPOSECODE, PURPOSEDESCRIPTION) VALUES (5,44004, 'CLP2004', 'Initial Contact with Alleged Victim');

INSERT INTO DM_DIMCONTACTPURPOSE (DIMPURPOSEKEY,CONTACTLOGID, PURPOSECODE, PURPOSEDESCRIPTION) VALUES (6,44005, 'CLP8000', 'Assessment Discussion Entry');

INSERT INTO DM_DIMCONTACTPURPOSE (DIMPURPOSEKEY,CONTACTLOGID, PURPOSECODE, PURPOSEDESCRIPTION) VALUES (7,44006, 'CLP8001', 'MDT Conference Entry');

INSERT INTO DM_DIMCONTACTPURPOSE (DIMPURPOSEKEY,CONTACTLOGID, PURPOSECODE, PURPOSEDESCRIPTION) VALUES (8,44007, 'CLP8002', 'Visitation Log Entry');

INSERT INTO DM_DIMCONTACTPURPOSE (DIMPURPOSEKEY,CONTACTLOGID, PURPOSECODE, PURPOSEDESCRIPTION) VALUES (9,44008, 'CLP8003', 'Other');

INSERT INTO DM_DIMCONTACTPURPOSE (DIMPURPOSEKEY,CONTACTLOGID, PURPOSECODE, PURPOSEDESCRIPTION) VALUES (10,44009, 'CLP8500', 'Treatment Planning');

INSERT INTO DM_DIMCONTACTPURPOSE (DIMPURPOSEKEY,CONTACTLOGID, PURPOSECODE, PURPOSEDESCRIPTION) VALUES (11,44010, 'CLP8501', 'Discharge Planning');

INSERT INTO DM_DIMCONTACTPURPOSE (DIMPURPOSEKEY,CONTACTLOGID, PURPOSECODE, PURPOSEDESCRIPTION) VALUES (12,44011, 'CLP8502', 'Supervision notes');

INSERT INTO DM_DIMCONTACTPURPOSE (DIMPURPOSEKEY,CONTACTLOGID, PURPOSECODE, PURPOSEDESCRIPTION) VALUES (13,44012, 'CLP8503', 'Referral Interview');

------------------------------------------------------------------------------------------------------------------------------

INSERT INTO DM_DIMCONTACTLOCATION (DIMCONTACTLOCATIONKEY, LOCATIONCODE, LOCATIONDESCRIPTION) VALUES (1, 'CLL2000', 'Home');

INSERT INTO DM_DIMCONTACTLOCATION (DIMCONTACTLOCATIONKEY, LOCATIONCODE, LOCATIONDESCRIPTION) VALUES (2, 'CLL2001', 'School');

INSERT INTO DM_DIMCONTACTLOCATION (DIMCONTACTLOCATIONKEY, LOCATIONCODE, LOCATIONDESCRIPTION) VALUES (3, 'CLL2002', 'Office');

INSERT INTO DM_DIMCONTACTLOCATION (DIMCONTACTLOCATIONKEY, LOCATIONCODE, LOCATIONDESCRIPTION) VALUES (4, 'CLL2003', 'Hospital');

INSERT INTO DM_DIMCONTACTLOCATION (DIMCONTACTLOCATIONKEY, LOCATIONCODE, LOCATIONDESCRIPTION) VALUES (5, 'CLL2004', 'Other');

------------------------------------------------------------------------------------------------------------------------------

INSERT INTO DM_DIMPERSONROLE (DIMPERSONROLEKEY, ROLECODE, ROLEDESCRIPTION) VALUES (1, 'ROLE1', 'Alleged Victim');

INSERT INTO DM_DIMPERSONROLE (DIMPERSONROLEKEY, ROLECODE, ROLEDESCRIPTION) VALUES (2, 'ROLE2', 'Alleged Maltreater');

INSERT INTO DM_DIMPERSONROLE (DIMPERSONROLEKEY, ROLECODE, ROLEDESCRIPTION) VALUES (3, 'ROLE3', 'Child');

INSERT INTO DM_DIMPERSONROLE (DIMPERSONROLEKEY, ROLECODE, ROLEDESCRIPTION) VALUES (4, 'ROLE4', 'Adult');

INSERT INTO DM_DIMPERSONROLE (DIMPERSONROLEKEY, ROLECODE, ROLEDESCRIPTION) VALUES (5, 'ROLE5', 'Parent');

INSERT INTO DM_DIMPERSONROLE (DIMPERSONROLEKEY, ROLECODE, ROLEDESCRIPTION) VALUES (6, 'ROLE6', 'Caretaker');

INSERT INTO DM_DIMPERSONROLE (DIMPERSONROLEKEY, ROLECODE, ROLEDESCRIPTION) VALUES (7, 'ROLE7', 'Custodian');

------------------------------------------------------------------------------------------------------------------------------

INSERT INTO DM_DIMCOMPLIANCESTATUS (DIMCOMPLIANCESTATUSKEY,COMPLIANCESTATUSCODE, COMPLIANCESTATUSDESC) VALUES (1, 'CCS8000','Completed' );

INSERT INTO DM_DIMCOMPLIANCESTATUS (DIMCOMPLIANCESTATUSKEY,COMPLIANCESTATUSCODE, COMPLIANCESTATUSDESC) VALUES (2, 'CCS8001','Not Completed');

INSERT INTO DM_DIMCOMPLIANCESTATUS (DIMCOMPLIANCESTATUSKEY,COMPLIANCESTATUSCODE, COMPLIANCESTATUSDESC) VALUES (3, 'CCS8002','Canceled');

------------------------------------------------------------------------------------------------------------------------------

INSERT INTO DM_DIMFREQUENCYCRITERIA (DIMFREQUENCYCRITERIAKEY,FREQUENCYCRITERIACODE,FREQUENCYCRITERIADESC) VALUES (1,'FC6','Bi-Weekly');

INSERT INTO DM_DIMFREQUENCYCRITERIA (DIMFREQUENCYCRITERIAKEY,FREQUENCYCRITERIACODE,FREQUENCYCRITERIADESC) VALUES (2,'FC7','Yearly');

INSERT INTO DM_DIMFREQUENCYCRITERIA (DIMFREQUENCYCRITERIAKEY,FREQUENCYCRITERIACODE,FREQUENCYCRITERIADESC) VALUES (3,'FC8','Half Yearly');

INSERT INTO DM_DIMFREQUENCYCRITERIA (DIMFREQUENCYCRITERIAKEY,FREQUENCYCRITERIACODE,FREQUENCYCRITERIADESC) VALUES (4,'FC4','Fortnightly');

INSERT INTO DM_DIMFREQUENCYCRITERIA (DIMFREQUENCYCRITERIAKEY,FREQUENCYCRITERIACODE,FREQUENCYCRITERIADESC) VALUES (5,'FC3','Monthly');

INSERT INTO DM_DIMFREQUENCYCRITERIA (DIMFREQUENCYCRITERIAKEY,FREQUENCYCRITERIACODE,FREQUENCYCRITERIADESC) VALUES (6,'FC9','Once Off');

INSERT INTO DM_DIMFREQUENCYCRITERIA (DIMFREQUENCYCRITERIAKEY,FREQUENCYCRITERIACODE,FREQUENCYCRITERIADESC) VALUES (7,'FC1','Daily');

INSERT INTO DM_DIMFREQUENCYCRITERIA (DIMFREQUENCYCRITERIAKEY,FREQUENCYCRITERIACODE,FREQUENCYCRITERIADESC) VALUES (8,'FC2','Weekly');

INSERT INTO DM_DIMFREQUENCYCRITERIA (DIMFREQUENCYCRITERIAKEY,FREQUENCYCRITERIACODE,FREQUENCYCRITERIADESC) VALUES (9,'FC5','Quarterly');

-------------------------------------------------------------------------------------------------------------------------------------------

INSERT INTO DM_DIMALGFINDING (DIMALGFINDINGKEY,FINDINGCODE,FINDINGDESC) VALUES (1,'FN1','Substantiated');

INSERT INTO DM_DIMALGFINDING (DIMALGFINDINGKEY,FINDINGCODE,FINDINGDESC) VALUES (2,'FN2','Unsubstantiated');

INSERT INTO DM_DIMALGFINDING (DIMALGFINDINGKEY,FINDINGCODE,FINDINGDESC) VALUES (3,'FN3','Indicated');

-----------------------------------------------------------------------------------------------------------------------

INSERT INTO DM_DIMALGTYPE (DIMALGTYPEKEY,ALGTYPECODE,ALGTYPEDESC) VALUES (1,'ALG1','Neglect / Deprivation');

INSERT INTO DM_DIMALGTYPE (DIMALGTYPEKEY,ALGTYPECODE,ALGTYPEDESC) VALUES (2,'ALG2','Physical Abuse');

INSERT INTO DM_DIMALGTYPE (DIMALGTYPEKEY,ALGTYPECODE,ALGTYPEDESC) VALUES (3,'ALG3','Benefit Fraud');

INSERT INTO DM_DIMALGTYPE (DIMALGTYPEKEY,ALGTYPECODE,ALGTYPEDESC) VALUES (4,'ALG4','Sexual Abuse');

INSERT INTO DM_DIMALGTYPE (DIMALGTYPEKEY,ALGTYPECODE,ALGTYPEDESC) VALUES (5,'ALG5','Child Abuse');

INSERT INTO DM_DIMALGTYPE (DIMALGTYPEKEY,ALGTYPECODE,ALGTYPEDESC) VALUES (6,'ALG6','Provider Violation');

INSERT INTO DM_DIMALGTYPE (DIMALGTYPEKEY,ALGTYPECODE,ALGTYPEDESC) VALUES (7,'ALG8250','Emotional Maltreatment');

----------------------------------------------------------------------------------------------------------------------

INSERT INTO DM_DIMALGLOCATION (DIMALGLOCATIONKEY,ALGLOCATIONCODE,ALGLOCATIONDESC) VALUES (1,'ALL1','Home');

INSERT INTO DM_DIMALGLOCATION (DIMALGLOCATIONKEY,ALGLOCATIONCODE,ALGLOCATIONDESC) VALUES (2,'ALL2','School');

INSERT INTO DM_DIMALGLOCATION (DIMALGLOCATIONKEY,ALGLOCATIONCODE,ALGLOCATIONDESC) VALUES (3,'ALL3','Office');

INSERT INTO DM_DIMALGLOCATION (DIMALGLOCATIONKEY,ALGLOCATIONCODE,ALGLOCATIONDESC) VALUES (4,'ALL4','Hospital');

INSERT INTO DM_DIMALGLOCATION (DIMALGLOCATIONKEY,ALGLOCATIONCODE,ALGLOCATIONDESC) VALUES (5,'ALL8250','Own Home');

INSERT INTO DM_DIMALGLOCATION (DIMALGLOCATIONKEY,ALGLOCATIONCODE,ALGLOCATIONDESC) VALUES (6,'ALL8251','Home Of Relative');

INSERT INTO DM_DIMALGLOCATION (DIMALGLOCATIONKEY,ALGLOCATIONCODE,ALGLOCATIONDESC) VALUES (7,'ALL8252','Foster Home');

INSERT INTO DM_DIMALGLOCATION (DIMALGLOCATIONKEY,ALGLOCATIONCODE,ALGLOCATIONDESC) VALUES (8,'ALL8253','Respite Home');

INSERT INTO DM_DIMALGLOCATION (DIMALGLOCATIONKEY,ALGLOCATIONCODE,ALGLOCATIONDESC) VALUES (9,'ALL8254','Group Home');

INSERT INTO DM_DIMALGLOCATION (DIMALGLOCATIONKEY,ALGLOCATIONCODE,ALGLOCATIONDESC) VALUES (10,'ALL8255','Nursing Home');

INSERT INTO DM_DIMALGLOCATION (DIMALGLOCATIONKEY,ALGLOCATIONCODE,ALGLOCATIONDESC) VALUES (11,'ALL8256','Public School');

INSERT INTO DM_DIMALGLOCATION (DIMALGLOCATIONKEY,ALGLOCATIONCODE,ALGLOCATIONDESC) VALUES (12,'ALL82562','Institution');

INSERT INTO DM_DIMALGLOCATION (DIMALGLOCATIONKEY,ALGLOCATIONCODE,ALGLOCATIONDESC) VALUES (13,'ALL8257','Private School');

INSERT INTO DM_DIMALGLOCATION (DIMALGLOCATIONKEY,ALGLOCATIONCODE,ALGLOCATIONDESC) VALUES (14,'ALL8258','Day Care');

INSERT INTO DM_DIMALGLOCATION (DIMALGLOCATIONKEY,ALGLOCATIONCODE,ALGLOCATIONDESC) VALUES (15,'ALL8259','Detention facility');

INSERT INTO DM_DIMALGLOCATION (DIMALGLOCATIONKEY,ALGLOCATIONCODE,ALGLOCATIONDESC) VALUES (16,'ALL8260','Shelter facility');

INSERT INTO DM_DIMALGLOCATION (DIMALGLOCATIONKEY,ALGLOCATIONCODE,ALGLOCATIONDESC) VALUES (17,'ALL8261','Residential Facility');

INSERT INTO DM_DIMALGLOCATION (DIMALGLOCATIONKEY,ALGLOCATIONCODE,ALGLOCATIONDESC) VALUES (18,'ALL8263','Pre-Adoptive Placement');

INSERT INTO DM_DIMALGLOCATION (DIMALGLOCATIONKEY,ALGLOCATIONCODE,ALGLOCATIONDESC) VALUES (19,'ALL8264','Day camp');

INSERT INTO DM_DIMALGLOCATION (DIMALGLOCATIONKEY,ALGLOCATIONCODE,ALGLOCATIONDESC) VALUES (20,'ALL8265','Residential camp');

INSERT INTO DM_DIMALGLOCATION (DIMALGLOCATIONKEY,ALGLOCATIONCODE,ALGLOCATIONDESC) VALUES (21,'ALL8266','Hospital or Clinic');

INSERT INTO DM_DIMALGLOCATION (DIMALGLOCATIONKEY,ALGLOCATIONCODE,ALGLOCATIONDESC) VALUES (22,'ALL8267','Other');

INSERT INTO DM_DIMALGLOCATION (DIMALGLOCATIONKEY,ALGLOCATIONCODE,ALGLOCATIONDESC) VALUES (23,'ALL8268','Unknown');

-----------------------------------------------------------------------------------------------------------------------

INSERT INTO DM_DIMALGSEVERITY (DIMALGSEVERITYKEY,SEVERITYCODE,SEVERITYDESC) VALUES (1,'HRM_TYPE01','High');

INSERT INTO DM_DIMALGSEVERITY (DIMALGSEVERITYKEY,SEVERITYCODE,SEVERITYDESC) VALUES (2,'HRM_TYPE02','Medium');

INSERT INTO DM_DIMALGSEVERITY (DIMALGSEVERITYKEY,SEVERITYCODE,SEVERITYDESC) VALUES (3,'HRM_TYPE03','Low');

------------------------------------------------------------------------------------------------------------------------

INSERT INTO DM_DIMRECORDSTATUS (DIMRECORDSTATUSKEY,RECORDSTATUSCODE,RECORDSTATUSDESC) VALUES (1,'RST1','Active');

INSERT INTO DM_DIMRECORDSTATUS (DIMRECORDSTATUSKEY,RECORDSTATUSCODE,RECORDSTATUSDESC) VALUES (2,'RST2','Canceled');

------------------------------------------------------------------------------------------------------------------------

INSERT INTO DM_DIMALGMETHOD (DIMALGMETHODKEY,ALGMETHODCODE,ALGMETHODDESC) VALUES (1,'ALM1','Phone');

INSERT INTO DM_DIMALGMETHOD (DIMALGMETHODKEY,ALGMETHODCODE,ALGMETHODDESC) VALUES (2,'ALM2','Email');

INSERT INTO DM_DIMALGMETHOD (DIMALGMETHODKEY,ALGMETHODCODE,ALGMETHODDESC) VALUES (3,'ALM3','Letter');

INSERT INTO DM_DIMALGMETHOD (DIMALGMETHODKEY,ALGMETHODCODE,ALGMETHODDESC) VALUES (4,'ALM4','Fax');

-------------------------------------------------------------------------------------------------------------------------

INSERT INTO DM_DIMRECURRENCE (DIMRECURRENCEKEY,CODE,DESCRIPTION) VALUES ( 1,'CCS_REC02','No Recurrence');

INSERT INTO DM_DIMRECURRENCE (DIMRECURRENCEKEY,CODE,DESCRIPTION) VALUES ( 2,'CCS_REC03','Maltreatment Recurrence');

---------------------------------------------------------------------------------------------------------------------------

INSERT INTO DM_DIMREPORTINGTIMELINESS(DIMREPORTINGTIMELINESSKEY,REPORTINGTIMELINESSKEYCODE,REPORTINGTIMELINESSKEYDESC) VALUES (1,'ROT','Reported On Time');

INSERT INTO DM_DIMREPORTINGTIMELINESS(DIMREPORTINGTIMELINESSKEY,REPORTINGTIMELINESSKEYCODE,REPORTINGTIMELINESSKEYDESC) VALUES (2,'RL','Reported Late');

INSERT INTO DM_DIMREPORTINGTIMELINESS(DIMREPORTINGTIMELINESSKEY,REPORTINGTIMELINESSKEYCODE,REPORTINGTIMELINESSKEYDESC) VALUES (3,'NA','Not Related to Compliance');

-------------------------------------------------------------------------------------------------------------------------

