------------------------------------------------------------------------------

-- all demo data in this file is shipped as sample, these objects are 

-- subject to change without notice, do not create custom dependencies 

-- on sample or demo objects

------------------------------------------------------------------------------

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(1,'0 - 19',0,19,'0-19','Core','Core');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(2,'20 - 29',20,29,'20-29','Core','Core');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(3,'30 - 39',30,39,'30-39','Core','Core');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(4,'40 - 49',40,49,'40-49','Core','Core');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(5,'50 - 59',50,59,'50-59','Core','Core');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(6,'60 - 69',60,69,'60-69','Core','Core');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(7,'70 - 79',70,79,'70-79','Core','Core');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(8,'over 80',80,100,'>80','Core','Core');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(9,'0 - 1',0,1,'0-1','Child','CG10005');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(10,'2 - 5',2,5,'2-5','Child','CG10005');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(11,'6 - 11',6,11,'6-11','Child','CG10005');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(12,'12 - 15',12,15,'12-15','Child','CG10005');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(13,'16 - 19',16,19,'16-19','Child','CG10005');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(14,'under 20',0,20,'<20','Adult','CG10005');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(15,'20 - 29',20,29,'20-29','Adult','CG10005');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(16,'30 - 39',30,39,'30-39','Adult','CG10005');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(17,'40 - 49',40,49,'40-49','Adult','CG10005');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(18,'over 49',49,100,'>49','Adult','CG10005');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(19,'Under 1',0,1,'<1','CG1','CG1');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(20,'1 - 5',1,5,'1-5','CG1','CG1');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(21,'6 - 12',6,12,'6-12','CG1','CG1');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(22,'13 - 14',13,14,'13-14','CG1','CG1');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(23,'15 - 18',15,18,'15-18','CG1','CG1');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(24,'19 - 20',19,20,'19-20','CG1','CG1');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(25,'21 - 44',21,44,'21-44','CG1','CG1');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(26,'45 - 64',45,64,'45-64','CG1','CG1');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(27,'65 - 74',65,74,'65-74','CG1','CG1');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(28,'75 - 84',75,84,'75-84','CG1','CG1');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(29,'over 85',85,200,'>85','CG1','CG1');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(30,'AGE GROUP UNKNOWN',0,0,'Unknown','CG1','CG1');

--------------------------------------------------------------

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(31,'0 - 3',0,3,'0-3','CCS','CCS');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(32,'4 - 7',4,7,'4-7','CCS','CCS');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(33,'8 - 11',8,11,'8-11','CCS','CCS');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(34,'12 - 15',12,15,'12-15','CCS','CCS');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(35,'16 - 19',16,19,'16-19','CCS','CCS');

INSERT INTO DM_AGEGROUPS (ID,GROUPNAME,STARTAGE,ENDAGE,GROUPDESCRIPTION,BUSAREA,PROGRAMCODE) VALUES(36,'over 19',20,200,'>19','CCS','CCS');

