------------------------------------------------------------------------------

-- all demo data in this file is shipped as sample, these objects are 

-- subject to change without notice, do not create custom dependencies 

-- on sample or demo objects

------------------------------------------------------------------------------

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (1,48574,1,25,16,12,3,10,1,3,1,2,2);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (1,48612,1,16,21,6,11,11,1,3,2,2,1);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (1,48639,1,21,12,21,12,1,2,1,3,5,4);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (1,48682,1,12,48,4,40,7,1,3,10,12,2);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (1,448705,2,48,23,31,6,1,1,3,3,32,1);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (1,48750,1,23,31,12,20,1,2,1,2,5,4);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (2,48574,2,132,138,4,10,9,1,3,5,12,1);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (2,48612,2,138,114,30,6,6,1,3,6,3,1);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (2,48639,1,114,92,42,20,1,2,3,1,4,1);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (2,48682,1,92,98,4,10,1,1,3,2,6,1);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (2,448705,1,98,83,21,6,3,1,3,12,1,3);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (2,48750,1,83,91,12,20,1,2,3,1,7,1);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (3,48574,1,25,16,12,3,10,1,3,1,2,2);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (3,48612,1,16,21,6,11,11,1,3,1,2,1);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (3,48639,1,21,13,20,12,1,2,1,1,5,4);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (3,48682,3,13,28,4,19,2,4,3,6,12,7);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (3,448705,3,28,19,10,1,1,1,3,10,2,6);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (3,48750,2,19,27,12,20,1,2,1,6,1,9);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (4,48574,3,63,78,4,19,2,4,3,1,12,7);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (4,48612,3,78,69,10,1,1,1,3,5,12,6);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (4,48639,3,69,77,12,20,1,2,8,6,4,9);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (4,48682,1,77,83,4,10,1,1,3,1,2,1);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (4,448705,1,83,78,11,6,3,1,3,1,2,3);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (4,48750,1,78,86,12,20,1,2,3,1,4,1);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (5,48574,1,105,125,10,30,4,1,3,1,6,1);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (5,48612,1,125,264,11,150,1,1,3,1,7,3);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (5,48639,1,264,272,42,50,1,2,3,1,8,1);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (5,48682,1,272,278,4,10,7,1,3,1,2,2);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (5,448705,1,278,273,11,6,1,1,3,1,2,1);

INSERT INTO DM_AGGCASEMONTH (ORGUNITKEY,TIMEPERIODKEY,DIMPRODUCTKEY,NOCASESONHANDBEGIN,NOCASESONHANDEND,NOCASESCLEARED,NOCASESRECEIVED,AVGDAYSCLEARED,AVGDAYSOPENTOSUB,AVGDAYSSUBTOAPPRV,AVGDAYSOPENTOACTIV,AVGDAYSRECEIPTTOREG,AVGDAYSREGTOACTIV) VALUES (5,48750,1,273,281,12,20,1,2,1,1,5,4);

