------------------------------------------------------------------------------

-- all demo data in this file is shipped as sample, these objects are 

-- subject to change without notice, do not create custom dependencies 

-- on sample or demo objects

------------------------------------------------------------------------------

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48615,1,21,1,'101','Enquiry');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48615,1,14,2,'102','Fraud Investigation');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,448705,1,12,3,'103','Review Qualifications');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48615,1,3,4,'104','Enquiry');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48682,1,7,5,'105','Fraud Investigation');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,448705,1,9,6,'106','Review Qualifications');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48615,1,3,7,'107','Enquiry');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48615,1,5,8,'108','Fraud Investigation');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,448705,1,8,9,'109','Review Qualifications');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48615,1,25,10,'110','Enquiry');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,448705,1,6,11,'111','Fraud Investigation');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,448705,1,30,12,'112','Review Qualifications');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48615,1,21,13,'113','Enquiry');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48615,1,14,14,'114','Fraud Investigation');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48615,1,12,15,'115','Review Qualifications');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48615,1,3,16,'116','Enquiry');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48682,1,7,17,'117','Fraud Investigation');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,448705,1,9,18,'118','Review Qualifications');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48615,1,3,19,'119','Enquiry');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48615,4,5,20,'120','Fraud Investigation');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,448705,1,8,21,'121','Review Qualifications');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48615,1,25,22,'122','Enquiry');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,448705,1,6,23,'123','Fraud Investigation');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,448705,1,30,24,'124','Review Qualifications');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48615,1,21,25,'125','Enquiry');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48615,1,14,26,'126','Fraud Investigation');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48615,1,12,27,'127','Review Qualifications');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48615,1,3,28,'128','Enquiry');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48682,1,7,29,'129','Fraud Investigation');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,448705,1,9,30,'130','Review Qualifications');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48615,1,3,31,'131','Enquiry');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48615,1,5,32,'132','Fraud Investigation');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,448705,1,8,33,'133','Review Qualifications');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48682,1,25,34,'134','Enquiry');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48682,1,6,35,'135','Fraud Investigation');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48682,1,30,36,'136','Review Qualifications');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48682,1,21,37,'137','Enquiry');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48615,1,14,38,'138','Fraud Investigation');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,448705,1,12,39,'139','Review Qualifications');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48615,1,3,40,'140','Enquiry');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48682,1,7,41,'141','Fraud Investigation');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,448705,1,9,42,'142','Review Qualifications');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48682,1,3,43,'143','Enquiry');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48615,1,5,44,'144','Fraud Investigation');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48682,1,8,45,'145','Review Qualifications');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48615,1,25,46,'146','Enquiry');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,448705,1,6,47,'147','Fraud Investigation');

INSERT INTO DM_FACTCASEEVENT (DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES(1,48682,1,30,48,'148','Review Qualifications');

-----------------------------------------------------------------------------------------------------------

--CCS DATA ---------------

-------------------------------------------------------------------------

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	1	,	1	,	3001	,	'1'	,	'Review Qualifications'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	2	,	2	,	3002	,	'2'	,	'Review Qualifications'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	3	,	3	,	3003	,	'3'	,	'Review Qualifications'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	4	,	4	,	3004	,	'4'	,	'Review Qualifications'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	5	,	5	,	3005	,	'5'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	1	,	6	,	3006	,	'6'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	1	,	7	,	3007	,	'7'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	2	,	-1	,	1	,	8	,	3008	,	'8'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	2	,	-1	,	1	,	9	,	3009	,	'9'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	2	,	-1	,	4	,	10	,	3010	,	'10'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	2	,	-1	,	1	,	11	,	3011	,	'11'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	2	,	-1	,	1	,	12	,	3012	,	'12'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	2	,	-1	,	1	,	13	,	3013	,	'13'	,	'Fraud Investigation'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	3	,	-1	,	3	,	14	,	3014	,	'14'	,	'Fraud Investigation'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	3	,	15	,	3015	,	'15'	,	'Fraud Investigation'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	3	,	16	,	3016	,	'16'	,	'Fraud Investigation'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	3	,	17	,	3017	,	'17'	,	'Fraud Investigation'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	3	,	18	,	3018	,	'18'	,	'Fraud Investigation'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	3	,	19	,	3019	,	'19'	,	'Fraud Investigation'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	5	,	20	,	3020	,	'20'	,	'Fraud Investigation'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	5	,	21	,	3021	,	'21'	,	'Fraud Investigation'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	5	,	22	,	3022	,	'22'	,	'Fraud Investigation'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	5	,	23	,	3023	,	'23'	,	'Fraud Investigation'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	3	,	24	,	3024	,	'24'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	2	,	25	,	3025	,	'25'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	3	,	26	,	3026	,	'26'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	2	,	27	,	3027	,	'27'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	2	,	-1	,	2	,	28	,	3028	,	'28'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	2	,	-1	,	1	,	29	,	3029	,	'29'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	2	,	-1	,	1	,	30	,	3030	,	'30'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	2	,	-1	,	1	,	31	,	3031	,	'31'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	2	,	-1	,	1	,	32	,	3032	,	'32'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	2	,	-1	,	1	,	33	,	3033	,	'33'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	3	,	-1	,	3	,	34	,	3034	,	'34'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	2	,	-1	,	3	,	35	,	3035	,	'35'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	2	,	-1	,	3	,	36	,	3036	,	'36'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	2	,	-1	,	3	,	37	,	3037	,	'37'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	2	,	-1	,	4	,	38	,	3038	,	'38'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	4	,	39	,	3039	,	'39'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	4	,	40	,	3040	,	'40'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	5	,	41	,	3041	,	'41'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	5	,	42	,	3042	,	'42'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	3	,	43	,	3043	,	'43'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	1	,	-1	,	3	,	44	,	3044	,	'44'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	2	,	-1	,	3	,	45	,	3045	,	'45'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	2	,	-1	,	3	,	46	,	3046	,	'46'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	2	,	-1	,	3	,	47	,	3047	,	'47'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	2	,	-1	,	3	,	48	,	3048	,	'48'	,	'Enquiry'	);

INSERT INTO DM_FACTCASEEVENT(DIMCASEREVIEWOUTCOMEKEY,EVENTDATEKEY,DIMINTEGRATEDCASETYPEKEY,COUNT,CASEID,CASEREFERENCENO,CASEEVENTTYPE) VALUES (	2	,	-1	,	3	,	49	,	3049	,	'49'	,	'Enquiry'	);

