------------------------------------------------------------------------------

-- all demo data in this file is shipped as sample, these objects are 

-- subject to change without notice, do not create custom dependencies 

-- on sample or demo objects

------------------------------------------------------------------------------

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48615,3,1,1,-1,1,1,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48917,3,1,2,-1,1,2,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48920,3,1,3,-1,1,3,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48921,3,1,4,-1,1,1,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48922,3,1,5,-1,1,2,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48923,3,1,6,-1,1,3,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48925,3,1,7,-1,1,7,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48926,3,1,8,-1,1,8,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48927,3,1,9,-1,1,1,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48928,3,1,10,-1,1,7,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48929,3,1,11,-1,1,8,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48930,3,1,12,-1,1,2,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48931,3,1,13,-1,1,1,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48933,3,1,114,-1,1,1,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48934,3,1,115,-1,1,2,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48935,3,1,116,-1,1,3,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48936,3,1,117,-1,1,1,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48937,3,1,118,-1,1,2,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48938,3,1,119,-1,1,3,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48939,3,1,1111,-1,1,3,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48941,3,1,1112,-1,1,7,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48942,3,1,1113,-1,1,8,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48943,3,1,23,-1,1,7,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48944,3,1,24,-1,1,8,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48945,3,1,25,-1,1,7,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48946,3,1,26,-1,1,3,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48947,3,1,27,-1,1,1,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48949,3,1,28,-1,1,2,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT (ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID)VALUES (48950,3,1,29,-1,1,3,-1,1,3);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,	3,1,	3001,	1	,3001,	2,	-1	,30001,	3,'101',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,	3,1,	3002,	2	,3002,	2,	-1	,30002,	3,'102',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,	3,1,	3003,	2	,3003,	2,	-1	,30003,	3,'103',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,	3,1,	3004,	2	,3004,	2,	-1	,30004,	3,'104',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,	3,1,	3005,	2	,3005,	2,	-1	,30005,	3,'105',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,	3,1,	3006,	1	,3006,	2,	-1	,30006,	3,'106',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,	3,1,	3007,	2	,3007,	2,	-1	,30007,	3,'107',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,	3,1,	3008,	2	,3008,	2,	-1	,30008,	3,'108',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,	3,1,	3009,	2	,3009,	2,	-1	,30009,	3,'109',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,	3,1,	3010,	2	,3010,	2,	-1	,30010,	3,'110',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,	3,1,	3011,	2	,3011,	2,	-1	,30011,	3,'111',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,	3,1,	3012,	2	,3012,	2,	-1	,30012,	3,'112',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,	3,1,	3016,	2	,3016,	2,	-1	,30016,	3,'116',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,	3,1,	3017,	4	,3017,	2,	-1	,30017,	3,'117',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,	3,1,	3018,	-1	,3018,	2,	-1	,30018,	3,'118',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,	3,1,	3021,	-1	,3021,	2,	-1	,30021,	3,'121',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,	3,1,	3022,	-1	,3022,	2,	-1	,30022,	3,'122',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,	3,1,	3023,	-1	,3023,	2,	-1	,30023,	3,'123',	1	);						

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,	3,1,	3024,	-1	,3024,	2,	-1	,30024,	3,'124',	1	);						

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	3025,	1	,3025,	2,	-1	,30025,	3,'125',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	3026,	2	,3026,	2,	-1	,30026,	3,'126',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	3027,	2	,3027,	2,	-1	,30027,	3,'127',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	3028,	2	,3028,	2,	-1	,30028,	3,'128',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	3029,	2	,3029,	2,	-1	,30029,	3,'129',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	3030,	1	,3030,	2,	-1	,30030,	3,'130',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	3031,	2	,3031,	2,	-1	,30031,	3,'131',	1	);

------------------------------------

-----------------------------------

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	4001,	1	,3001,	2,	-1	,31001,	3,'1101',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	4002,	2	,3002,	2,	-1	,31002,	3,'1102',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	4003,	2	,3003,	2,	-1	,31003,	3,'1103',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	4004,	2	,3004,	2,	-1	,31004,	3,'1104',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	4005,	2	,3005,	2,	-1	,31005,	3,'1105',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	4006,	1	,3006,	2,	-1	,31006,	3,'1106',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	4007,	2	,3007,	2,	-1	,31007,	3,'1107',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	4008,	2	,3008,	2,	-1	,31008,	3,'1108',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	4009,	2	,3009,	2,	-1	,31009,	3,'1109',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	4010,	2	,3010,	2,	-1	,31010,	3,'1110',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	4011,	2	,3011,	2,	-1	,31011,	3,'1111',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	4012,	2	,3012,	2,	-1	,31012,	3,'1112',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	4016,	2	,3016,	2,	-1	,31016,	3,'1116',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	4017,	4	,3017,	2,	-1	,31017,	3,'1117',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	4018,	-1	,3018,	2,	-1	,31018,	3,'1118',	1	);

------------------------

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	4021,	-1	,3024,	2,	-1	,31019,	3,'1119',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	4022,	-1	,3025,	2,	-1	,31020,	3,'1120',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	4023,	-1	,3021,	2,	-1	,31021,	3,'1121',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	4024,	-1	,3022,	2,	-1	,31022,	3,'1122',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	4025,	-1	,3023,	2,	-1	,31023,	3,'1123',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	4026,	-1	,3022,	2,	-1	,31024,	3,'1124',	1	);

INSERT INTO DM_FACTCASEPARTICIPANT(ACTIVESTARTDATEKEY,DIMCASEPARTROLEID,ISMASTERKEY,PERSONHISTORYKEY,RELATIONSHIPTYPEKEY,MASTERPERSONHISTORYKEY,DIMPRODUCTKEY,ACTIVEENDDATEKEY,CASEID,PRIMCLIENTCASEPARTROLEID,CASEREFERENCENO,COUNT) VALUES (	48615,		3,1,	4027,	-1	,3023,	2,	-1	,31025,	3,'1125',	1	);

