puts "About to validate ${prm.oraclemodule}"
OMBCONNECT  %CONNECT% 

OMBCC '%REPORTING_NAME%/%OWB_MODULE_NAME%'
OMBVALIDATE ORACLE_MODULE '%OWB_MODULE_NAME%' OUTPUT VALIDATION_RESULT TO '%VAILDATE_LOG_DIR%' WRITE(ERROR,WARNING, SUCCESS)
OMBCOMMIT    
puts "Finished."
