puts "About to validate %REPORTING_NAME%/%OWB_MODULE_NAME%"
OMBCONNECT  %CONNECT% USE WORKSPACE '%CURAM_WORKSPACE%'

OMBCC '%REPORTING_NAME%'
OMBVALIDATE ORACLE_MODULE '%OWB_MODULE_NAME%' OUTPUT VALIDATION_RESULT TO '%VAILDATE_LOG_DIR%' WRITE(ERROR,WARNING, SUCCESS)
OMBCOMMIT    
puts "Finished."
