INSERT INTO  DM_PROPERTIES  (BIPROPERTYID , BICATEGORY , BIPROP_NAME,BIPROP_VALUE ,BIPROP_TYPE ,DEFAULTVALUE ,LOCALE ,LASTWRITTEN ) VALUES (dmpropertiesseq.nextval, 'CONFIG','BI.UNDEFINED','Undefined','STRING',NULL,'en',dm_getDateTime());

